### ISSUE TITLE
Output File as an option

### ISSUE THREAD

**Issue by leifg** [jeremyjh/dialyxir#101]
The tool [pronto-dialyzer](https://github.com/iurifq/pronto-dialyzer) adds PR comments to Dialyzer violations.

It relies on an output file rather than running the dialyzer.

For this tool it would be great to pass in the `--outfile` argument.

I realize you can output all dialyzer output via `mix dialyzer 2>&1 > dialyzer.out` but that means that all other outputs (such as the output of enabled apps etc...) will also be written to that file.

**Comment by jeremyjh** [comment]
What exactly would you want in the output files, is it the structured output you'd get from `dialyzer --raw` ?

**Comment by leifg** [comment]
I don't know `dialyzer --raw` looks like but basically everything that is printed to STDERR from `mix dialyzer` would be great.

**Comment by asummers** [comment]
Could this not simply be redirected? `mix dialyzer > file.txt`. Seems like it could be useful independently, but that seems an OK workaround to me.

**Comment by jeremyjh** [comment]
I think the `--quiet` flag may solve this as well - with that flag all that is emitted are warnings - or nothing if there are none. You could redirect that to a file right?

**Comment by kenny-evitt** [comment]
@jeremyjh One (minor) reason why this option would be nice is that I could then 'shadow' the Mix task with an alias that automatically saves the warnings output to stderr. That'd be a little nicer than running `mix dialyzer 2> dialyzer-warnings` by hand. (In a script, that longer command is fine.)

I'm using the `dialyzer-warnings` file as a task list so it'd be nice to automatically update it every time I run the Mix task.

**Comment by jeremyjh** [comment]
I wouldn't be opposed to a PR that adds this as an CLI option.

**Comment by kenny-evitt** [comment]
@jeremyjh Great! I'll try to work on a PR soonish.
