### ISSUE TITLE
File path omitted in 'unknown type'

### ISSUE THREAD

**Issue by evnu** [jeremyjh/dialyxir#102]
The output for the following module does not indicate the location of the type error. Is this fixable or due to a restriction in Elixir?

```elixir
defmodule Outer do
  @type t :: DoesNotExist.t
end
```

Output (with dialyxir "~> 0.5"):

```
$ mix dialyzer
Checking PLT...  
[:compiler, :elixir, :kernel, :logger, :stdlib]
PLT is up to date!
Starting Dialyzer
dialyzer args: [check_plt: false,
 init_plt: '/tmp/error/_build/dev/dialyxir_erlang-20.0.1_elixir-1.5.1_deps-dev.plt',
 files_rec: ['/tmp/error/_build/dev/lib/error/ebin'],
 warnings: [:unknown]]
done in 0m0.98s
:0: Unknown type 'Elixir.DoesNotExist':t/0
```

The same result is generated when using a `@spec`:

```elixir
defmodule Outer do
  @spec foo() :: DoesNotExist.t
  def foo() do
    :ok
  end
end
```

**Comment by uberbrodt** [comment]
I'm seeing something similar on OTP 20/Elixir 1.4.5 
```
:0: Unknown type 'Elixir.Integer':t/0
```
(Obviously it was a mistake in the typespec, but the lack of file path and line number is the issue)

**Comment by jeremyjh** [comment]
@evnu @uberbrodt This is inherent behavior of the Erlang `dialyzer`; it will do the same thing for erlang sources dialyzed from the command-line.  The output we get from `:dialyzer.run` for the example given is:

```elixir
[{:warn_unknown, {[], 0}, {:unknown_type, {DoesNotExist, :t, 0}}}]
```

There is no source information included, so I don't think there is really anything we can do here.

**Comment by lok0613** [comment]
Really is this the way to use Elixir? Suppress every warning but not try solving it?

**Comment by jtrees** [comment]
This appears to have been fixed in OTP24.
