### ISSUE TITLE
"has an opaque subtype" error message

### ISSUE THREAD

**Issue by davich** [jeremyjh/dialyxir#104]
Hi, can someone help me decode this error message

> The specification for 'Elixir.XXX':stop_words/0 has an opaque subtype 'Elixir.MapSet':t(binary()) which is violated by the success typing () -> #{'__struct__':='Elixir.MapSet', 'map':=#{binary()=>'true'}}

I'm calling `MapSet.difference(words, @stop_words)`, which are both MapSets of Strings.

It seems to come from the second argument being a constant (module attribute).

Thanks

**Comment by davich** [comment]
Just a note: the MapSets are created like MapSet.new(~w(a b c))

**Comment by davich** [comment]
Just a note: the MapSets are created like `MapSet.new(~w(a b c))`

**Comment by davich** [comment]
`The call 'Elixir.MapSet':difference('Elixir.MapSet':t(_),#{'__struct__':='Elixir.MapSet', 'map':=#{<<_:8,_:_*8>>=>'true'}}) does not have an opaque term of type 'Elixir.MapSet':t(_) as 2nd argument`

I think when I create a MapSet as a module attribute it changes it from the opaque type Elixir.MapSet into its struct format #{'__struct__':='Elixir.MapSet', ...}. Which means it doesn't match with the typespec in the MapSet module.

Does anyone know how to keep it as the opaque type?

**Comment by jeremyjh** [comment]
@davich the underlying representation is always a struct.  The `@opaque` type is used only by `dialyzer`, not by the runtime. I think what is happening is that your module attribute doesn't have a type annotation, and at runtime it cannot be traced back to the Map.new call which did carry that annotation. Attributes are evaluate at compile time. You could run your attribute through another call to Map.new before calling difference on it. Maybe make a helper function that just returns that attribute after calling Map.new on it. Then `dialyzer` should have the type relation.

**Comment by davich** [comment]
Thank you for your quick and informative reply!
I tried it with your suggestion of passing the module attribute mapset into MapSet.new in the method (which appears to be a no-op in the MapSet source code), and that works well.

I take it there's no way to add a type annotation to a module attribute? Is that correct?

Thanks

**Comment by jeremyjh** [comment]
> I take it there's no way to add a type annotation to a module attribute? Is that correct?
That's right, `@spec` can only be applied to functions.

**Comment by davich** [comment]
Thank you!
