### ISSUE TITLE
Not using Dialyzer Incrementally

### ISSUE THREAD

**Issue by lswith** [jeremyjh/dialyxir#105]
Dialyzer can be used incrementally but it seems that Dialyxir isn't using it as such. I would like to give Dialyxir the existing plt files had build any others incrementally.

**Comment by jeremyjh** [comment]
Sorry, can you be a bit more specific? What exactly do you want it to do differently? It does use a shared base PLT and incrementally add other modules as dependencies are added to the project.

**Comment by jeremyjh** [comment]
This can be re-opened with more specific feedback. Dialyzer does not support incremental analysis in its public API (ElixirLS uses internal functions), and using multiple PLT files at runtime may be unsound as the separate PLTs do not share their types with each other. I'm not sure if you are talking about either of those possible features.

**Comment by crova** [comment]
Hey @jeremyjh , how is it going?

First of all, thank you very much for this package.

In one of the projects I'm working, we would be interested in using the [new --incremental flag](https://github.com/erlang/otp/pull/5997) that got introduced on Dialyzer.

I'm not sure what would be needed to get this working here but I would be willing to give any help I can towards that goal.

Do you reckon is something we can look forward to get implemented?

Cheers.

**Comment by jeremyjh** [comment]
A PR would be welcome once it is in an OTP release.

**Comment by crova** [comment]
Thanks for the feedback.
I'll see if I can get acquainted with this situation to submit the PR when the time comes.
Any pointers on what to look for is much appreciated.

Cheers.

**Comment by codeadict** [comment]
I'm interested on this too, can submit a PR if i get some time soon. If anyone else is interested, this is how they added it on Rebar3 https://github.com/erlang/rebar3/pull/2736
