### ISSUE TITLE
Building PLTs hangs.

### ISSUE THREAD

**Issue by squaresurf** [jeremyjh/dialyxir#106]
I have an umbrella app that doesn't seem to be able to build PLTs. It seems to work, then just keeps churning away at the `Adding 1165 modules to dialyxir_erlang-20.1_elixir-1.5.2_deps-dev.plt` step. I used the `mix dialyzer --plt` command and waited nearly 24 hours to no avail. I've also tried many different combinations of cli switches and mix config values to add dev/test apps. I am able to successfully run dialyzer on a different project of mine (which may use a different version of elixir/erlang). Since I get no error output I'm not really sure where to start debugging this. Would someone point me in the direction of where to start debugging this?

**Comment by jeremyjh** [comment]
Most likely you are running out of memory. Did you look at memory utilization of your beam process?

**Comment by squaresurf** [comment]
I was able to fix the issue by changing the `plt_add_deps` which lowered the number of deps. I do think that I was running out of memory.

```diff
-        plt_add_deps: :transitive,
+        plt_add_deps: :app_tree,
```
