### ISSUE TITLE
Add dialyzer.clean task

### ISSUE THREAD

**Issue by christhekeele** [jeremyjh/dialyxir#107]
Adding the ability to `rm` all plts by running `mix dialyzer.clean` would be very useful, especially in CI environments.

This also keeps end users from having to know where `dialyxir` happens to place its plts for any given version (even though this is not likely to change).

Finally, if other `mix dialyzer` task-adding tools do the same, it creates a really nice API where you don't even have to know which tool you are using to purge plts. To that end I've duplicated this feature request here as well: Comcast/dialyzex#1.

**Comment by jeremyjh** [comment]
I agree its a good idea.

**Comment by jeremyjh** [comment]
@christhekeele Do you picture any arguments being relevant to this task? For example should it be possible to clean just both the current configuration (current elixir, erlang version PLTs) versus PLTs from all versions (e.g. `--all`). I think if there are not any command line switches specific to this task, then this task itself should just be a command-line switch (similar to `--plt`). This is to avoid needless pollution of the `mix help` space.

**Comment by christhekeele** [comment]
- I can't think of any relevant generic flags, and specific ones (ie what gets cleaned) are inherently dialyxir-implementation specific
- I feel as if the flag-based approach is less generic than the task-based one, which defeats some of the cross-dialyzer-task-parity I had in mind for this
- The task needn't appear in `mix help` if it lacks a description, so long as it is well documented within the project

YMMV, though, but that's what I've been envisioning: a simple, single, generic cross-tool API.

**Comment by jeremyjh** [comment]
I don't think a cross-tool API will really be of much benefit to anyone right now, and isn't really worth pursuing as a design goal. Where it doesn't have any other costs I'm not opposed to it though.

Its an interesting idea to hide the task via doc, but I wonder if this would make the documentation a bit awkward as we'd really need to document `dialyzer.clean` in the `dialyzer` task's doc.  Maybe burying the task is a problem too though; the `--plt` flag seems to escape a lot of people's notice.

Right now I'm leaning towards implementing this under a flag `--clean` to be consistent with `--plt`.

**Comment by christhekeele** [comment]
I do feel as if `--clean` is more consistent with the `--plt` flag today, although I'll admit I'm not a huge fan of using flags in lieu of subtasks. In my opinion subtasks are easier to invoke programmatically and flags should be for configuration rather than behaviour selection. This is completely personal preference, though, I'm happy to have just the flags should that be your preference.

**Comment by jeremyjh** [comment]
>  although I'll admit I'm not a huge fan of using flags in lieu of subtasks. 

I'm not not either actually. The current state is more evolved than designed. Originally there were two tasks, `dialyzer.plt` only built the plt, `dialyzer` only did analysis and would complain about lacking plt. I came to the realization that this was stupid: if a program knows something needs to be done, it should just do it. So the `dialyzer` task became a one-shot deal, it figures out what needs to be done, and does it. 

I did not anticipate anyone would actually want to sometimes just build a PLT, so removed that task entirely. When it was requested again, I decided this was more a variant of the `dialyzer` task; just like you could run it with `--no-check` of the plt, you could check `--plt` only. `--clean` is obviously something different entirely, and begs the `--plt` question as well. I guess maybe I've come back around to your original point-of-view, that three tasks is the right answer, with `--plt` left for compatibility.

**Comment by christhekeele** [comment]
Ah, that makes sense. The three-task API does make some sense to me, although perhaps 4 might be more resilient to future feature requests? Just using prior work for naming within mix task suites:

- `mix dialyzer.build` - generate the PLTs
- `mix dialyzer.run` - perform the analysis
- `mix dialyzer` - both those things above
- `mix dialyzer.clean` - remove the PLTs

**Comment by christhekeele** [comment]
Just ran into another understated reason to prefer subtasks: they are able to be used in a `mix.exs` task alias the way parameterized flags are not.

**Comment by gnufede** [comment]
Hello, I'm working on the `mix dialyzer.clean` task and I'm about to open the PR.

It doesn't remove the PLTs but instead it removes the modules from the PLT, in a similar fashion as `mix dialyzer` only calling [plt_remove](https://github.com/jeremyjh/dialyxir/blob/master/lib/dialyxir/plt.ex#L174) instead of `plt_check`.

Would that be the correct approach?

**Comment by jeremyjh** [comment]
@gnufede I don't think so - I think the desire is to actually remove the files. Removing modules happens automatically each time the task is run - if the applications have changed and modules no longer are needed, they get removed. I think `dialyzer.clean` needs to delete any PLTs that matches the directories and file name convention currently in use.

**Comment by gnufede** [comment]
Thank you @jeremyjh, I'll work on that approach then

**Comment by jeremyjh** [comment]
Implemented in #116
