### ISSUE TITLE
Add dialyzer.build task

### ISSUE THREAD

**Issue by christhekeele** [jeremyjh/dialyxir#108]
Adding the ability to explicitly build the plts without running ***any*** dialyzer checks would be helpful for warming up caches in CI environments. This would be especially useful if your CI doesn't allow for configuring test task timeout but is more generous during the installation phase; or if it allows for extending task timeout but you want to know if for some reason your dialyzer *checking* time takes forever (independent of the plt build time).

It's also the logical inverse of the `dialyzer.clean` task proposed in #107, and I love symmetry.

This could also be called `dialyzer.compile`.

Alternately it could instead be registered *under* the `compile` namespace to allow this to occur automatically alongside other compilation tasks when `mix compile` is run, perhaps under the name `compile.plts` or `compile.dialyzer`. I'm inclined to avoid that though since that could unexpectedly make project compile times skyrocket in environments where dialyzer users aren't anticipating it.

**Comment by jeremyjh** [comment]
This is already supported and documented,  `mix dialyzer --plt`.

**Comment by christhekeele** [comment]
Discussion prompting reopening this in #107.

**Comment by gnufede** [comment]
You can close this issue now, as [https://github.com/jeremyjh/dialyxir/pull/115](https://github.com/jeremyjh/dialyxir/pull/115) is merged
