### ISSUE TITLE
Failure Analyzing on Erlang 20 + Elixir 1.6.1

### ISSUE THREAD

**Issue by jvantuyl** [jeremyjh/dialyxir#113]
Running on Mac with Homebrew.  While I am not entirely sure that it's related, I just upgraded Erlang (version 20.2.4).  Elixir package hasn't seen an upgrade yet.  Reasonably sized project.  Was analyzing fine on some older versions (Erlang versions 20.2.2 and 20.2.3, Elixir 1.6.1).  New version builds PLTs fine, but fails with this error:

```
Checking PLT...
[:asn1, :bbmustache, :certifi, :compiler, :crypto, :dialyxir, :distillery,
 :earmark, :elixir, :erlexec, :ex_aws, :ex_aws_s3, :ex_doc, :excoveralls,
 :exexec, :exjsx, :exlager, :gen_state_machine, :goldrush, :hackney, :httpoison,
 :idna, :jsx, :kernel, :lager, :logger, :metrics, :mimerl, :mix, :poison,
 :public_key, :ssl, :ssl_verify_fun, :stdlib, :sweet_xml, :syntax_tools,
 :table_rex, :unicode_util_compat, :uuid, :xmerl]
PLT is up to date!
Starting Dialyzer
dialyzer args: [
  check_plt: false,
  init_plt: '/Users/jvantuyl/devel/<REDACTED>/_build/dev/dialyxir_erlang-20.2.4_elixir-1.6.1_deps-dev.plt',
  files_rec: ['/Users/jvantuyl/devel/<REDACTED>/_build/dev/lib/<REDACTED>/ebin'],
  warnings: [:unmatched_returns, :error_handling, :race_conditions, :unknown]
]
:dialyzer.run error: Analysis failed with error:
{function_clause,[{lists,do_flatten,
                         [40643,[]],
                         [{file,"lists.erl"},{line,627}]},
                  {lists,do_flatten,2,[{file,"lists.erl"},{line,630}]},
                  {dialyzer_races,var_type_analysis,6,
                                  [{file,"dialyzer_races.erl"},{line,2263}]},
                  {dialyzer_races,fixup_race_forward,14,
                                  [{file,"dialyzer_races.erl"},{line,566}]},
                  {dialyzer_races,fixup_race_forward,14,
                                  [{file,"dialyzer_races.erl"},{line,692}]},
                  {dialyzer_races,fixup_race_forward_pullout,14,
                                  [{file,"dialyzer_races.erl"},{line,394}]},
                  {dialyzer_races,fixup_race_list,3,
                                  [{file,"dialyzer_races.erl"},{line,340}]},
                  {dialyzer_races,race,1,
                                  [{file,"dialyzer_races.erl"},{line,308}]}]}
Last messages in the log cache:
  Reading files and computing callgraph... done in 0.41 secs
  Removing edges... done in 0.02 secs

18:42:45.457 [error] Process #PID<0.1618.0> raised an exception
** (FunctionClauseError) no function clause matching in :lists.do_flatten/2
    (stdlib) lists.erl:627: :lists.do_flatten(40643, [])
    (stdlib) lists.erl:630: :lists.do_flatten/2
    dialyzer_races.erl:2263: :dialyzer_races.var_type_analysis/6
    dialyzer_races.erl:566: :dialyzer_races.fixup_race_forward/14
    dialyzer_races.erl:692: :dialyzer_races.fixup_race_forward/14
    dialyzer_races.erl:394: :dialyzer_races.fixup_race_forward_pullout/14
    dialyzer_races.erl:340: :dialyzer_races.fixup_race_list/3
    dialyzer_races.erl:308: :dialyzer_races.race/1
```

This occurs even after I regenerate all of the PLTs.

Here's the `uname -a` on the Mac, if that helps:
```
Darwin jvantuyl-mb15 15.6.0 Darwin Kernel Version 15.6.0: Tue Jan  9 20:12:05 PST 2018; root:xnu-3248.73.5~1/RELEASE_X86_64 x86_64
```

I also attempted it on a Linux VM with the older version 20.2 of Erlang and Elixir 1.6.1.  It gave the same error down to the line numbers.  As such, I'm unclear if the problem is triggered by my code or the upgrades.

**Comment by jeremyjh** [comment]
I think you've found a bug in Erlang, you should report it there. But, I'd remove `:race_conditions` and see if that fixes it. Really that isn't a very useful warning and I don't recommend using it anymore.

**Comment by sdwolfz** [comment]
Try installing elixir [from source](https://elixir-lang.org/install.html#compiling-from-source-unix-and-mingw) after you upgrade erlang. If you get the same error again it's definitely a bug. I don't know how homebrew or your linux distribution prepares the elixir package but if it uses the precompiled archives instead of installing from source you could get such errors from time to time.

**Comment by jvantuyl** [comment]
Okay, this just got more interesting...  I'm going to give you all the details here (for any poor soul that finds this in the future).  That said, I'm closing this because I think you're right that this is a bug in Erlang...

I've locked it down to one changeset in my code that triggers it.  The function that makes it angry looks like this:

```
  def handle_call({:insert, root, path, data}, _, repo) do
    true = :ets.insert(repo, {[root|path], data})
    {:reply, :ok, repo}
  end
```

And this makes it magically work:

```
  def handle_call({:insert, root, path, data}, _, repo) do
    full_path = [root|path]
    true = :ets.insert(repo, {full_path, data})
    {:reply, :ok, repo}
  end
```

Corner case in parsing?

**Comment by jeremyjh** [comment]
That - should not happen. This may be an Elixir compiler bug, but there should not be any valid BEAM code you can feed `:dialyzer` that should make it crash.
