### ISSUE TITLE
plt_core_path option ignored

### ISSUE THREAD

**Issue by ShepBook** [jeremyjh/dialyxir#114]
Hello!

I'm trying to have my plts placed in a location outside $MIX_HOME, so I was looking at the plt_core_path option.

Here is the snippet from my def project section in my mix.exs:

```
def project do
    [
      app: :my_app,
      dialyzer: [
        plt_add_deps: :transitive,
        plt_core_path: "../../_build/plt"
      ],
      version: "0.0.1",
      build_path: "../../_build",
      config_path: "../../config/config.exs",
      deps_path: "../../deps",
      lockfile: "../../mix.lock",
      elixir: "~> 1.4",
      elixirc_paths: elixirc_paths(Mix.env()),
      start_permanent: Mix.env() == :prod,
      aliases: aliases(),
      test_coverage: [tool: ExCoveralls],
      preferred_cli_env: [
        coveralls: :test,
        "coveralls.detail": :test,
        "coveralls.post": :test,
        "coveralls.html": :test
      ],
      deps: deps()
    ]
  end
```

Given that `mix.exs` is nested in `my_app/apps/my_app/mix.exs`, I would expect it to use `my_app/_build/plt` for storing my core plts. However, the plts still end up in my `~/.mix` directory. For my build CI system, I don't seem to be able to cache things from outside my project directory (`~/my_app`), so I can't grab the plts in `~/.mix`.

Any thoughts on why this might not work as I'd hoped it would. I did try setting `plt_core_path: "_build/plt"` we well, but that didn't change anything either.

Thanks!

**Comment by jeremyjh** [comment]
This is explained in the documentation, but `:plt_core_path` overrides the default MIX_HOME location for the Erlang and Elixir Core PLTs. `:plt_path` is used to set the path to store your project's plt.

**Comment by ShepBook** [comment]
So, if I use `:plt_core_path` I should expect it to put the PLTs that are built in that location?

Or is it only used for referencing already built PLTs?

**Comment by jeremyjh** [comment]
@ShepBook The core files are only built when required, and are only required when your project does not have an existing PLT, in which case they are copied to your project to use as a base. So if you change `:plt_core_path` but your PLT is still in _build/dev then indeed nothing will change.
