### ISSUE TITLE
Dialyzer not covers all clauses in function

### ISSUE THREAD

**Issue by tim2CF** [jeremyjh/dialyxir#119]
```elixir
  @spec hello(integer()) :: map()
  def hello(int) do
    case int do
      1 -> :foo
      _ -> :wtf
    end
  end
```
then
```
Iljas-iMac:hello timcf$ mix dialyzer
Compiling 1 file (.ex)
Checking PLT...
[:compiler, :elixir, :kernel, :logger, :stdlib]
PLT is up to date!
Starting Dialyzer
dialyzer args: [
  check_plt: false,
  init_plt: '/Users/timcf/tmp/hello/_build/dev/dialyxir_erlang-20.3.2_elixir-1.6.4_deps-dev.plt',
  files_rec: ['/Users/timcf/tmp/hello/_build/dev/lib/hello/ebin'],
  warnings: [:unknown]
]
done in 0m1.08s
lib/hello.ex:16: Invalid type specification for function 'Elixir.Hello':hello/1. The success typing is (_) -> 'foo' | 'wtf'
done (warnings were emitted)
Iljas-iMac:hello timcf$
```
but if 
```elixir
  @spec hello(integer()) :: map()
  def hello(int) do
    case int do
      1 -> %{hello: "world"}
      _ -> :wtf
    end
  end
```
then
```
Iljas-iMac:hello timcf$ mix dialyzer
Compiling 1 file (.ex)
Checking PLT...
[:compiler, :elixir, :kernel, :logger, :stdlib]
PLT is up to date!
Starting Dialyzer
dialyzer args: [
  check_plt: false,
  init_plt: '/Users/timcf/tmp/hello/_build/dev/dialyxir_erlang-20.3.2_elixir-1.6.4_deps-dev.plt',
  files_rec: ['/Users/timcf/tmp/hello/_build/dev/lib/hello/ebin'],
  warnings: [:unknown]
]
done in 0m1.07s
done (passed successfully)
```

**Comment by tim2CF** [comment]
function spec will fail in some cases
```elixir
  @spec hello(integer()) :: map()
  def hello(int) do
    case int do
      1 -> %{hello: "world"}
      _ -> :wtf
    end
  end
```
when `int != 1`
But dialyzer not generates any warnings here ...

**Comment by tim2CF** [comment]
Why it not generates any warnings when there is clause where wrong value is returned from function?

**Comment by jeremyjh** [comment]
I think the answer is that dialyzer will only report cases where the typing MUST fail. If it is possible for some inputs to succeed the typing and it does not know that it must use an input that fails the typing, then it will not report an issue. This goes back to the success typing strategy, which unfortunately is quite limited in some cases.

**Comment by timCF** [comment]
Oh, thanks.. it's not very good for me :(
It would be perfect if there will be flag to generate warnings when at least one possible clause has incorrect type. So I think, I have to address this question to Dialyzer team, but lat commit to Dialyzer github repo was 5 years ago :)
https://github.com/erlang-labs/dialyzer

**Comment by jeremyjh** [comment]
No dialyzer is part of the core Erlang distribution and they update it all the time with bug fixes. I doubt they can address this issue as its more of a foundational success typing limitation but you can certainly ask.

https://github.com/erlang/otp/tree/master/lib/dialyzer
