### ISSUE TITLE
Error parsing warning with multiple different arguments

### ISSUE THREAD

**Issue by axelson** [jeremyjh/dialyxir#165]
Here's the output from `mix dialyzer`

Please file a bug in https://github.com/jeremyjh/dialyxir/issues with this message.

Failed to parse warning:
`
[{:"(", 1}, {:atom_full, 1, '\'start\''}, {:",", 1}, {:variable_alias, 1, 'Vcompile@1::map(),Vruntime@1'}, {:::, 1}, {:atom_part, 1, 'm'}, {:atom_part, 1, 'a'}, {:atom_part, 1, 'p'}, {:"(", 1}, {:")", 1}, {:")", 1}]
`

Legacy warning:
apps/web_interface/lib/web_interface/endpoint.ex:1: The call 'Elixir.Timber.Integrations.PhoenixInstrumenter':phoenix_channel_receive('start',Vcompile@1::map(),Vruntime@1::map()) will never return since it differs in the 1st and 3rd argument from the success typing arguments: ('stop',any(),'ok')

**Comment by asummers** [comment]
Thank you!

**Comment by asummers** [comment]
Interesting! It seems to be over-eager on the variable alias regex. I have unit tests for this now, so this should be fixed in the next day or so.

**Comment by axelson** [comment]
Great, thanks!
