### ISSUE TITLE
mix dialyzer.explain task?

### ISSUE THREAD

**Issue by jeremyjh** [jeremyjh/dialyxir#173]
@asummers I should have thought of this before you implemented `--list` but I'm actually kind of thinking that for consistency and to promote visibility of the feature we should make a new task `dialyzer.explain`, and include current functionality of `--explain` and `--list` there. 

The main benefit is it gets its own mention in `mix help` but also there is an idea to reserve flags for modifications to the core task - so `--format` fits, `--list` doesn't, and `--plt` doesn't either. See discussion at https://github.com/jeremyjh/dialyxir/issues/107#issuecomment-350887771
.

`--plt` I'm thinking will get softly deprecated, meaning it simply isn't mentioned in the help or README, so people will just discover `dialyzer.build`.

**Comment by asummers** [comment]
Ah interesting. I'm totally open to a new API around that. Just as long as the functionality exists.

**Comment by asummers** [comment]
Closed via #189
