### ISSUE TITLE
inconsistency with OTP release numbers?

### ISSUE THREAD

**Issue by herenowcoder** [jeremyjh/dialyxir#18]
Hi!

Looks like OTP guys stopped increasing otp_release number.
Eg. 17.1 has actually still "17" when you call erlang:system_info(otp_release).

This screws up your check in plt_file()
So maybe another kind of check is needed.
I also don't have any idea if this is intented behavior in OTP and it will continue in the whole 17.x line, or not.

Any ideas? :)

**Comment by jeremyjh** [comment]
I'm not planning to do anything about this, but I would be open to a PR.
