### ISSUE TITLE
Hex bump RC1

### ISSUE THREAD

**Issue by asummers** [jeremyjh/dialyxir#194]
@jeremyjh mind bumping? Should eliminate a bunch of the issues people are opening after the merge this morning.

**Comment by jeremyjh** [comment]
Agreed, I was just waiting to see if that last one was fixed in master.

**Comment by asummers** [comment]
Makes sense 😄

**Comment by asummers** [comment]
Still throughly confused why my PR fixed anything, I'll have to investigate that at some point.

**Comment by asummers** [comment]
If anything, I should have just gotten a better error message, but that last guy's issue was legitimately fixed in #192... Unsure how that's possible. Is it possible the original hex push wasn't pulled master?

**Comment by jeremyjh** [comment]
I don't see how that is possible, no because the version in `mix.exs` is used by hex to publish it. So it wouldn't show up in hex.pm with that version number unless it were based on those sources.

I was also surprised it fixed anything, I wonder is it swallowing a warning now for them? 

Push of rc.1 is literally blocked on this issue: https://github.com/hexpm/hexpm/issues/690

**Comment by asummers** [comment]
I buy the mix.exs argument. Just trying to think outside the box for that. 

I'd share your suspicion of the error swallow except it seemed like the same error was printing the actual message after that point. I'm very confused. 

Hex errors are no bueno :(

**Comment by asummers** [comment]
Additionally the rescue even being necessary is completely confusing because the lexing error was being explicitly thrown/caught.

**Comment by jeremyjh** [comment]
I thought the lexing error was thrown by Erlang code? That would always be an exception that must be rescued.

**Comment by asummers** [comment]
https://github.com/jeremyjh/dialyxir/blob/master/lib/dialyxir/pretty_print.ex

`lex/1` is already doing that though. The tuple was that one being thrown. 

Then that was being explicitly caught in format_warning in 

https://github.com/jeremyjh/dialyxir/blob/master/lib/dialyxir/formatter.ex

**Comment by jeremyjh** [comment]
Ah, I see. Yeah I don't understand either then.

**Comment by jeremyjh** [comment]
rc.1 is published

**Comment by jeremyjh** [comment]
I know what the issue was; we didn't add the new files in src to the file list for Hex. So its only working when pulled via git. Will push a new RC shortly.

**Comment by asummers** [comment]
GOOD CALL!!!
