### ISSUE TITLE
Provide a way to ignore folder from elixir-ish ignore file

### ISSUE THREAD

**Issue by AndrewDryga** [jeremyjh/dialyxir#210]
Following up discussion on Slack it's sometimes desired to simply ignore warnings produced by tests and ignoring all warnings from `test/` folder would work for that.

With dialyzer ignore format you can just type a subpath: `/test/` and it would silence all warnings that mention that path.

**Comment by jeremyjh** [comment]
You really have to go out of your way to get warnings from tests...since they are `exs` files they are not compiled to BEAM files and dialyzer won't ever see them. Also we usually would not dialyze in MIX_ENV=test. Is this just an example, is there another case where you would want to ignore a portion of the path?

**Comment by asummers** [comment]
@jeremyjh test/support is a reasonable thing to want to dialyze. It's usually not in the dev compile path so wouldn't get covered by normal dialyzing.

**Comment by jeremyjh** [comment]
Sure, you could run dialyzer in MIX_ENV=test and then you would see warnings for compiled modules in test/support - but why would you do that and then ignore all of them? Sorry I guess I'm not following.

**Comment by mydearxym** [comment]
when dialyxir give me error about ExUnit, It's hard to debug ..

```bash
:0:unknown_function
Function ExUnit.Callbacks.__merge__/3 does not exist.
________________________________________________________________________________
:0:unknown_function
Function ExUnit.CaseTemplate.__proxy__/2 does not exist.
________________________________________________________________________________
:0:unknown_type
Unknown type: Error.t/0.
________________________________________________________________________________
:0:unknown_type
Unknown type: Result.Object.t/0.
________________________________________________________________________________
```

**Comment by jeremyjh** [comment]
@mydearxym are you running dialyzer in MIX_ENV=test ? Typically its run only in dev.

**Comment by AndrewDryga** [comment]
@jeremyjh there is a valid use case to run it with `MIX_ENV=test`. On CI there is no reason to compile the code twice and running dialyzer from test env saves some time, more for larger projects (I know some that have slow compilation time).

**Comment by asummers** [comment]
I'm a little unclear why the current ignore feature is insufficient. I think ignoring a folder will require us to come up with globbing rules, and making it easy to ignore large sections of a project doesn't sound like something we should be supporting at first glance. How many files are we talking about?

**Comment by jeremyjh** [comment]
I could see supporting a regex for matching the filename; the part I did not understand is why you'd dialyze in test and then ignore test modules but I think @AndrewDryga point is valid.

**Comment by mydearxym** [comment]
@jeremyjh  thanks for your explanation,  ExUnit error it's gone after i put `:ex_unit` in application.

as for .dialyzer_ignore.exs file,  i know is covered in README, but it just [not work](https://github.com/coderplanets/coderplanets_server/blob/dev/.dialyzer_ignore.exs) for me, i had tried put ignore file both in `root project dir` and `config dir` but no luck

not work:
```elixir
# .dialyzer_ignore.exs
[
  # {file, warning_type}
  {"lib/mastani_server/cms/utils/loader.ex", :no_return}
]
```
not work
```elixir
# .dialyzer_ignore.exs
[
  # {file}
  {"lib/mastani_server/cms/utils/loader.ex"}
]
```

**Comment by asummers** [comment]
You need to tell your `mix.exs` file that that's your ignore file. E.g.
```elixir
dialyxer: [
    ...
        ignore_warnings: ".dialyzer_ignore.exs"
],
```
Your issue is different from the topic of this original thread though, so please make a new issue for future questions around the ignore file.

**Comment by mydearxym** [comment]
@asummers  it worked , thanks!  sorry for bother though

**Comment by asummers** [comment]
No trouble!

**Comment by veverkap** [comment]
Is there a way in the dialyzer_ignore file to exclude mix dependencies?

**Comment by jeremyjh** [comment]
#256 adds support for regex expressions; since the path is part of the short warning message you could ignore all messages from test support with something like `[ ~r/^test\/.*/]` in your exs ignore file.
