### ISSUE TITLE
Warning Language Audit

### ISSUE THREAD

**Issue by asummers** [jeremyjh/dialyxir#220]
We should give each message a once over, particularly with respect to short message, so that we know that they make sense in real life.

- [x] `Dialyxir.Warnings.AppCall`
- [x] `Dialyxir.Warnings.Apply`
- [x] `Dialyxir.Warnings.BinaryConstruction`
- [x] `Dialyxir.Warnings.Call`
- [x] `Dialyxir.Warnings.CallToMissingFunction`
- [x] `Dialyxir.Warnings.CallWithOpaque`
- [x] `Dialyxir.Warnings.CallWithoutOpaque`
- [x] `Dialyxir.Warnings.CallbackArgumentTypeMismatch`
- [x] `Dialyxir.Warnings.CallbackInfoMissing`
- [x] `Dialyxir.Warnings.CallbackMissing`
- [x] `Dialyxir.Warnings.CallbackSpecArgumentTypeMismatch`
- [x] `Dialyxir.Warnings.CallbackSpecTypeMismatch`
- [x] `Dialyxir.Warnings.CallbackTypeMismatch`
- [x] `Dialyxir.Warnings.ContractDiff`
- [x] `Dialyxir.Warnings.ContractSubtype`
- [x] `Dialyxir.Warnings.ContractSupertype`
- [x] `Dialyxir.Warnings.ContractWithOpaque`
- [x] `Dialyxir.Warnings.ExactEquality`
- [x] `Dialyxir.Warnings.ExtraRange`
- [x] `Dialyxir.Warnings.FuncionApplicationArguments`
- [x] `Dialyxir.Warnings.FunctionApplicationNoFunction`
- [x] `Dialyxir.Warnings.GuardFail`
- [x] `Dialyxir.Warnings.GuardFailPattern`
- [x] `Dialyxir.Warnings.ImproperListConstruction`
- [x] `Dialyxir.Warnings.InvalidContract`
- [x] `Dialyxir.Warnings.MissingRange`
- [x] `Dialyxir.Warnings.NegativeGuardFail`
- [x] `Dialyxir.Warnings.NoReturn`
- [x] `Dialyxir.Warnings.OpaqueGuard`
- [x] `Dialyxir.Warnings.OpaqueEquality`
- [x] `Dialyxir.Warnings.OpaqueMatch`
- [x] `Dialyxir.Warnings.OpaqueNonequality`
- [x] `Dialyxir.Warnings.OpaqueTypeTest`
- [x] `Dialyxir.Warnings.OverlappingContract`
- [x] `Dialyxir.Warnings.PatternMatch`
- [x] `Dialyxir.Warnings.PatternMatchCovered`
- [x] `Dialyxir.Warnings.RaceCondition`
- [x] `Dialyxir.Warnings.RecordConstruction` (likely not possible)
- [x] `Dialyxir.Warnings.RecordMatching` (likely not possible)
- [x] `Dialyxir.Warnings.UnknownBehaviour`
- [x] `Dialyxir.Warnings.UnknownFunction`
- [x] `Dialyxir.Warnings.UnknownType`
- [x] `Dialyxir.Warnings.UnmatchedReturn`
- [x] `Dialyxir.Warnings.UnusedFunction`

**Comment by jeremyjh** [comment]
Resolved in #222
