### ISSUE TITLE
Deprecate :project and :transitive dependencies

### ISSUE THREAD

**Issue by jeremyjh** [jeremyjh/dialyxir#223]
These really only exist for backwards compatibility. Not sure if they should just be removed from docs or get a deprecation warning, but at least one new user on the forums was using `:transitive` so leaning towards a warning.

**Comment by asummers** [comment]
We use transitive in the code at work. Does it not actually do anything?

**Comment by jeremyjh** [comment]
Well what it does is include your mix dependency tree instead of your OTP dependency tree. This can easily include things you don't need, like dev tools.

**Comment by jeremyjh** [comment]
Yes that is how it works, but the default `app_tree` does the same thing but using OTP application trees. This is more inclusive in the sense it will also bring in OTP applications that are not specified in mix (such as `:mnesia`), and less inclusive in that it leaves out anything with `runtime: false`.  If people have OTP dependencies that are missing or not properly specified their deployment fails when using any OTP release package, so it could help you catch that earlier.

**Comment by asummers** [comment]
Interesting. I have no a priori reason to say no, then, I don't think.

**Comment by mguimas** [comment]
Well the docs say `:transitive - Include Mix and OTP application dependencies recursively`, so I am using `:transitive` to have Mix and its deps, and these deps' deps, and so on, and also my application deps tree.

If `:transitive` goes away how can I get the above effect?
