### ISSUE TITLE
Default ignore file?

### ISSUE THREAD

**Issue by jeremyjh** [jeremyjh/dialyxir#224]
Thinking of making `.dialyzer_ignore.exs` a default ignore file - if the file exists, we use it for ignores unless a different file is configured as the ignore file. This is something else people trip over. Also should probably update docs to make this more clearly the preferred format.

**Comment by asummers** [comment]
Hmmm. Would we want to also provide a little utility to generate one from the current warning output? Would make transitioning trivial.

**Comment by asummers** [comment]
Ping on that question @jeremyjh

**Comment by jeremyjh** [comment]
Sorry I missed the question. I don't think we can convert legacy warnings can we? The current warnings are a partial string match of `dialyzer`'s format and the new warnings are a complete match on the short description (unless I've missed something).

**Comment by asummers** [comment]
I'm pretty close to having a thing for the actual ticket description. Just am figuring out ways to not have it message the user a bunch of times.

**Comment by jeremyjh** [comment]
In one sense, I kind of agree that we do owe the user a heads-up that we are evaling arbitrary code in their project, but that is already the case since they have to run a compile before dialyzer can run. This is why I wanted to get it in before 1.0, I think it does change our contract.  On the other hand, if they already have a file named `.dialyzer-ignore.exs` then what else could it realistically be but a file they already created while using the release candidate?

I don't know I'd worry over-much about this. Maybe we put a notice there for rc.5 and remove it in 1.0?

**Comment by mguimas** [comment]
I think you are worrying too much regarding this "ignore warnings" topic, and showing too much information to the user.

It is preferable to be keep simple, and let the user know what `mix dialyzer` does regarding ignoring warnings via `mix help dialyzer` (put examples in the help, not the normal tools output).

I once add a teacher who kept saying: "Too much information is misinformation"
