### ISSUE TITLE
PLT Analysis Failed

### ISSUE THREAD

**Issue by erikreedstrom** [jeremyjh/dialyxir#233]
Suddenly seeing errors trying to run dialyzer now.

```
:dialyzer.run error: Analysis failed with error:
Could not scan the following file(s):
  Could not get Core Erlang code for: /Users/erikreedstrom/.asdf/installs/elixir/1.7.2/lib/mix/ebin/Elixir.Mix.beam
  Recompile with +debug_info or analyze starting from source code  Could not get Core Erlang code for: /Users/erikreedstrom/.asdf/installs/elixir/1.7.2/lib/mix/ebin/Elixir.Mix.TasksServer.beam
  Recompile with +debug_info or analyze starting from source code  Could not get Core Erlang code for: /Users/erikreedstrom/.asdf/installs/elixir/1.7.2/lib/mix/ebin/Elixir.Mix.Utils.beam
  Recompile with +debug_info or analyze starting from source code  Could not get Core Erlang code for: /Users/erikreedstrom/.asdf/installs/elixir/1.7.2/lib/mix/ebin/Elixir.Mix.Tasks.Xref.beam
...snip...
```
This results in no types or functions being available when running the task.

The only thing I've changed recently was a switch to OTP21/1.7.2.

Really stumped. Any help is appreciated! 🙇

**Comment by erikreedstrom** [comment]
Maybe related to this issue: https://github.com/elixir-lang/elixir/issues/5851#issuecomment-406874551

**Comment by asummers** [comment]
Try killing your _build. When you bump versions, sometimes you need to just compile everything fresh.

**Comment by erikreedstrom** [comment]
It was that my asdf installed elixir was using the base OTP version of 19.
Updated `.tool-versions` to
```
erlang 21.0.4
elixir 1.7.2-otp-21
```
and everything is working again!

Cheers! 🍻
