### ISSUE TITLE
Unknown warning: contract range

### ISSUE THREAD

**Issue by evnu** [jeremyjh/dialyxir#235]
I encountered the following unknown warning with dialyxir 1.0-rc3, which cannot be pretty-printed yet:

```
Please file a bug in https://github.com/jeremyjh/dialyxir/issues with this message.

Unknown warning:
:contract_range

Legacy warning:
apps/utils/lib/my_module.ex:103: The contract 'Elixir.MyModule':v1(timestamp::'Elixir.DateTime':t() | 'Elixir.Unixtime':t(),mac_address::<<_:136>>,clock_seq::<<_:14>>,format::'binary' | 'string') -> {'ok',uuid::t() | t_string()} | {'error',atom()}
    ; (timestamp::<<_:60>>,mac_address::'Elixir.MAC':t_bin(),clock_seq::<<_:14>>,format::'binary' | 'string') -> t() | t_string() cannot be right because the inferred return for v1(<<_:60>>,_mac_binary@1::<<_:48>>,<<_:14>>,_format@1::any()) on line 130 is {'error','wrong_argument'} | {'ok',<<_:128,_:_*160>>}
```

**Comment by asummers** [comment]
Huh interesting. Thought I had that one. I'll get it added soon.

**Comment by asummers** [comment]
@evnu is there a public project I can see this on by chance? Want to make sure my fix reads okay.

**Comment by evnu** [comment]
No, I don't have a public project with this issue. Testing on a branch sounds reasonable, maybe I can also find a small code snippet to produce the error.

**Comment by evnu** [comment]
Finding a small example is surprisingly complicated. I found an Erlang example on [stackoverflow](https://stackoverflow.com/a/11899970/436853), which produces this warning, but cannot get this to produce the same warning after converting it to Elixir.

**Comment by asummers** [comment]
No trouble! I have had that issue as well with certain errors. I'll push a branch and we can go from there.

**Comment by asummers** [comment]
https://github.com/jeremyjh/dialyxir/tree/contract-range-warning Here's the branch! Let me know if it looks okay for you. Should just be able to plug and play.

**Comment by evnu** [comment]
Looks perfect to me:

```
apps/utils/lib/my_module.ex:103:contract_range
Contract cannot be correct because return type on line number 130 is mismatched.

Function:
MyModule.v1(<<_::60>>, _mac_binary :: <<_::48>>, <<_::14>>, _format :: any())

Type specification:
Contract head: (
  timestamp :: DateTime.t() | Unixtime.t(),
  mac_address :: <<_::136>>,
  clock_seq :: <<_::14>>,
  format :: :binary | :string
) :: {:ok, uuid :: t() | t_string()} | {:error, atom()}Contract head: (
  timestamp :: <<_::60>>,
  mac_address :: MAC.t_bin(),
  clock_seq :: <<_::14>>,
  format :: :binary | :string
) :: uuid :: t() | t_string()

Success typing (line 130):
{:error, :wrong_argument} | {:ok, <<_::128, _::size(160)>>}
```

**Comment by asummers** [comment]
Great! I'm going to adjust one or two things in there and will get a PR out shortly.
