### ISSUE TITLE
Dialyzer task doesn't recompile

### ISSUE THREAD

**Issue by bbhoss** [jeremyjh/dialyxir#24]
It seems that the dialyzer task itself doesn't recompile. Every time I change my code I have to recompile manually, or I get the same warnings. Shouldn't the task do this for me?

**Comment by jeremyjh** [comment]
I don't remember the reason for this, but I think that there was one. I haven't used Elixir for a couple of years so I'm honestly not sure, but I think there is a bit of delay in running the compile task even if it has no work to do. I think my work-flow at the time had a compile happening on every file change.

I'm open to accepting a pull request that changes it, it should mention any overheads though.

One thing you can do which you may not know, is run multiple mix tasks in a single command invocation like this:

```
mix do compile, dialyze
```

**Comment by folz** [comment]
I'll +1 recompiling before dialyzer, since `mix test` also recompiles before running tests. It's just one less thing to remember.

**Comment by lpil** [comment]
:+1:
