### ISSUE TITLE
:0:unknown_function when using protocols

### ISSUE THREAD

**Issue by MichaelBitard** [jeremyjh/dialyxir#258]
When using protocols, dialyzer output some errors, even when @fallback_to_any true or when implementing for Any explicitely
```
defmodule Toto do
  defprotocol Name do
    @fallback_to_any true
    def name(id)
  end
  defimpl Toto.Name, for: Any do
    def name(id), do: id
  end
  defimpl Toto.Name, for: BitString do
    def name(id), do: id
  end
end

```

mix dialyzer (version 1.0.0-rc.3)
Output:

```:0:unknown_function
Function Toto.Name.Atom.__impl__/1 does not exist.
________________________________________________________________________________
:0:unknown_function
Function Toto.Name.Float.__impl__/1 does not exist.
________________________________________________________________________________
:0:unknown_function
Function Toto.Name.Function.__impl__/1 does not exist.
________________________________________________________________________________
:0:unknown_function
Function Toto.Name.Integer.__impl__/1 does not exist.
________________________________________________________________________________
:0:unknown_function
Function Toto.Name.List.__impl__/1 does not exist.
________________________________________________________________________________
:0:unknown_function
Function Toto.Name.Map.__impl__/1 does not exist.
________________________________________________________________________________
:0:unknown_function
Function Toto.Name.PID.__impl__/1 does not exist.
________________________________________________________________________________
:0:unknown_function
Function Toto.Name.Port.__impl__/1 does not exist.
________________________________________________________________________________
:0:unknown_function
Function Toto.Name.Reference.__impl__/1 does not exist.
________________________________________________________________________________
:0:unknown_function
Function Toto.Name.Tuple.__impl__/1 does not exist.
```

**Comment by asummers** [comment]
Hmmm. Can you try force recompile or delete `_build` and recompile? I think there's weird stuff with Protocol reconsolidation, so forcing it to do those operations might help.

**Comment by MichaelBitard** [comment]
I did all that, unfortunately nothing changed

**Comment by asummers** [comment]
This might actually be an Elixir bug propagating through to Dialyzer and bubbling up here. I've kind of minimized your already pretty minimal example and I can't get it to stop complaining:

```elixir
  defprotocol FooName do
    @fallback_to_any true

    def name(id)
  end

  defimpl FooName, for: Any do
    def name(id), do: id
  end
```

I know it's referencing that `defimpl` because when I take it away it gets mad. Even by removing the `@fallback_to_any` wrinkle, and using an example from the Elixir site, it gets upset.

```elixir
defprotocol Size do
  def size(data)
end

defimpl Size, for: BitString do
  def size(string), do: byte_size(string)
end
```

I can create the issue in Elixir later and I'll absolutely give you a shoutout for finding the issue. Basically the expectation is that when implementing a protocol, Dialyzer will not complain about missing implementations for the other types and the current behavio(u)r is obviously the opposite of that. I have confirmed this is an issue with OTP 21 and 22, as well as Elixir 1.7.1 and 1.7.3, so it doesn't appear new.

**Comment by jeremyjh** [comment]
Is htis the same issue as #221 ?

**Comment by jeremyjh** [comment]
Pretty sure it is the same issue. Its already been to Elixir as elixir-lang/elixir#7708

**Comment by asummers** [comment]
Yep. Jose closed my issue as already having been reported here. Shame on me for not looking through the issues here first =)

**Comment by MichaelBitard** [comment]
Sorry for the duplicate, I looked into the list before posting but it was not really clear for me that #221 was the same issue.

Closing mine

**Comment by asummers** [comment]
@MichaelBitard I didn't either, no worries =)
