### ISSUE TITLE
Ignore all files in a path

### ISSUE THREAD

**Issue by hylkealons** [jeremyjh/dialyxir#264]
I would like to disable dialyzer for all files in a folder. Is that currently possible?

**Comment by jeremyjh** [comment]
If you use master, there is support for regular expressions in your ignore file. Take a look our own ignore file for an example.

The text it matches on, is the warning emitted with `mix dialyzer --format short`, so you can check that then write a regex. Make sure you add the ignore file to your config (README explains it pretty well).

 Probably it would be something like:

.dialyzer-ignore.exs
```elixir
[ 
~r/^/path/to/my_folder.*/
]

**Comment by asummers** [comment]
Going to go ahead and close this since this is possible on master. If this is still an issue due to bugs, we can reopen.
