### ISSUE TITLE
Make available via hex.pm

### ISSUE THREAD

**Issue by NobbZ** [jeremyjh/dialyxir#27]
Why don't you publish to hex.pm, so one could specify `dialyxir` as a dev-dependency?

**Comment by lpil** [comment]
:+1:

**Comment by pspeter3** [comment]
This would be awesome.

**Comment by lpil** [comment]
:+1:

**Comment by CrowdHailer** [comment]
+1

**Comment by optikfluffel** [comment]
:+1:
They also have [a nice How-To](https://hex.pm/docs/publish) if it's the first thing you publish to Hex :smile_cat:

**Comment by my-flow** [comment]
+1

**Comment by johnhamelink** [comment]
:+1: Yes please!

**Comment by jeremyjh** [comment]
Hi, sorry for the long delay on this but it is finally published, see the updated README.

**Comment by lpil** [comment]
Thanks!
