### ISSUE TITLE
Error with Influx library. Could you Help the author.

### ISSUE THREAD

**Issue by laibulle** [jeremyjh/dialyxir#283]
### Precheck

* Be sure your versions of Dialyxir and Erlex are up to date.

### Environment

* Elixir & Erlang/OTP versions (elixir --version):

```
Erlang/OTP 21 [erts-10.1.1] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.7.4 (compiled with Erlang/OTP 21)
```

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir):

```
  "dialyxir": {:hex, :dialyxir, "1.0.0-rc.4", "71b42f5ee1b7628f3e3a6565f4617dfb02d127a0499ab3e72750455e986df001", [:mix], [{:erlex, "~> 0.1", [hex: :erlex, repo: "hexpm", optional: false]}], "hexpm"},
```

### Current behavior
Hello, I have opened an issue in this Repo, could you help the author to fix that ?

https://github.com/mneudert/instream/issues/46

I have an error when I use Influx

```
  use Instream.Connection, otp_app: :my_app
```

```
Function version/2 has no local returnElixirLS Dialyzer
Function version/0 has no local returnElixirLS Dialyzer
Function ping/2 has no local returnElixirLS Dialyzer
Function ping/0 has no local returnElixirLS Dialyzer
Function status/1 has no local returnElixirLS Dialyzer
Function version/1 has no local returnElixirLS Dialyzer
Function ping/1 has no local returnElixirLS Dialyzer
Function status/2 has no local returnElixirLS Dialyzer
Function status/0 has no local returnElixirLS Dialyzer
```

You can find the Connection source file here https://github.com/mneudert/instream/blob/master/lib/instream/connection.ex

### Expected behavior
I should not have any warning.

Best regard

**Comment by asummers** [comment]
I'm not positive why you're getting those errors at first glance in your project. All of those functions eventually call into `execute/2` so it might think that that `QueryPlanner.execute/3` function is misbehaving,. I would look there first and see if it has some edge case you're not considering. 

However that all said, we just wrap the Dialyzer errors with this library and reformat them. We don't actually have code in this project for generating the warnings themselves. Dialyzer upstream is mad at you about _something_ you're doing in that callchain, you just have to find what =) If you can't figure it out, we do allow ignoring specific errors with the `:ignore_warnings` opt. But for your case, that seems like a deep enough function for the application that figuring out why it's mad is probably the best call.

**Comment by asummers** [comment]
One technique I've found helpful is replacing the contents of e.g. that `QueryPlanner.execute` function with some known good sentinel value, then slowly re-adding in parts until you get the errors again in a binary search like fashion. In this way you can kind of narrow down where it's getting mad.  If after adding in the sentinel. you still get errors, you know it's higher up in the callstack.
