### ISSUE TITLE
REQ: Common CI Environment Recommendations

### ISSUE THREAD

**Issue by jherdman** [jeremyjh/dialyxir#288]
It seems a common problem people have is figuring out how to set up Dialyzer on their CI environment. Perhaps a section in the README or wiki explaining common steps to a fast(er) build would be nice?

**Comment by asummers** [comment]
Not sufficient for this, but I gave a talk recently on setting this up in e.g. Travis. We can probably lift things from it.

https://speakerdeck.com/asummers/pedantic-elixir-builds
