### ISSUE TITLE
Failed to format warning

### ISSUE THREAD

**Issue by kbaird** [jeremyjh/dialyxir#291]
### Precheck

* Take a look at the open issues and be sure that your issue is not already covered.
* Be sure your versions of Dialyxir and Erlex are up to date.

### Environment

* Elixir & Erlang/OTP versions (elixir --version):

Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]

Elixir 1.8.1 (compiled with Erlang/OTP 20)

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir):

"dialyxir": {:hex, :dialyxir, "1.0.0-rc.4", "71b42f5ee1b7628f3e3a6565f4617dfb02d127a0499ab3e72750455e986df001", [:mix], [{:erlex, "~> 0.1", [hex: :erlex, repo: "hexpm", optional: false]}], "hexpm"},

### Current behavior
 * Describe current behavior. Include errors, stack traces, and any additional information that might be important here.

Received this message:
```
Please file a bug in https://github.com/jeremyjh/dialyxir/issues with this message.

Failed to format warning:
"@spec a({:error, %{:conflict => :tag_parent_max}} | {:ok, %95{_ => _}}) :: :ok\ndef a() do\n  :ok\nend\n"


Legacy warning:
lib/inventory_service/tagging/lineage.ex:57: Expression produces a value of type {'error',#{'conflict':='tag_parent_max'}} | {'ok',#{'__struct__':=_, _=>_}}, but this value is unmatched
________________________________________________________________________________
done (warnings were emitted)
```

### Expected behavior

No error reported, or a standard understandable dialyzer type mismatch, as appropriate to the code being analyzed.

**Comment by asummers** [comment]
I think this is fixed in Erlex 0.2. Can you try bumping that and see if this still occurs?

**Comment by kbaird** [comment]
That fixed it, @asummers. Thank you.

**Comment by kbaird** [comment]
Spoke too soon. No, this is still an issue.

**Comment by asummers** [comment]
I see the bug. I'll try and fix and then bump Erlex this evening. 

Need to add a new special case to this list:
https://github.com/asummers/erlex/blob/master/lib/erlex.ex#L335

**Comment by asummers** [comment]
I fixed Erlex. Can you see if master works? You may have to `override: true`

`{:erlex, github: "asummers/erlex", override: true}` . I'll push a release up later, if so.

**Comment by kbaird** [comment]
That appears to have cleared up the `failed to format` warning. I suspect what I have left is a genuine dialyzer complaint about our code, but I'm not sure yet.

**Comment by asummers** [comment]
Yep. We print the messages we get, we don't generate extra ones. `Erlex 0.2.1` is published on Hex.
