### ISSUE TITLE
Failure when formatting warning (reported by Dialyxir)

### ISSUE THREAD

**Issue by whatyouhide** [jeremyjh/dialyxir#303]
### Precheck

* Take a look at the open issues and be sure that your issue is not already covered.
* Be sure your versions of Dialyxir and Erlex are up to date.

### Environment

* Elixir & Erlang/OTP versions (elixir --version):

```
Erlang/OTP 21 [erts-10.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.9.0-dev (c8e054a7f) (compiled with Erlang/OTP 20)
```

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir):

`1.0.0-rc.4`

### Current behavior
 * Describe current behavior. Include errors, stack traces, and any additional information that might be important here.

```
Failed to format warning:
"@spec a(%95{}) :: :ok\ndef a() do\n  :ok\nend\n"
```

**Comment by asummers** [comment]
Hi @whatyouhide :wave: 

I believe this is fixed on Erlex master, do you mind pulling that in instead of whatever version rc4 is pulling in and seeing if that makes your problem go away?

**Comment by whatyouhide** [comment]
It does! Thanks a lot. 💟
