### ISSUE TITLE
Dialyxir RC5?

### ISSUE THREAD

**Issue by asummers** [jeremyjh/dialyxir#304]
There have been sufficient bugfixes, I think, to warrant an rc5. Perhaps also making the min version of erlex 0.2.1?

**Comment by jeremyjh** [comment]
Yes and hopefully it can be the last RC. We don't need 100% parsing perfection IMO. I do want to include #222 in it as well though, that is RFR. And I agree let's set min erlex to the latest.

**Comment by jeremyjh** [comment]
https://hex.pm/packages/dialyxir/1.0.0-rc.5
