### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by PragTob** [jeremyjh/dialyxir#305]
:wave: 

thanks for dialyxir, it has improved tremendously over time! :clap: 

I think it'd be very cool to add a Changelog somewhere - rc.5 was just released and to know what was fixed/changed I gotta go through the commits right now which isn't really ideal :)

Maybe also after the 1.0 release (and for it) but I think changelogs are super helpful for users of a library.

Thanks! :green_heart:

**Comment by jeremyjh** [comment]
Agreed and thanks for the reminder. I will start one. `rc.5` is mostly bug fixes but also some short format warning updates which is worth noting as it may mean some ignore file updates are required.

**Comment by asummers** [comment]
Probably worth also linking to https://github.com/asummers/erlex/blob/master/CHANGELOG.md as that has noteworthy relevant changes.

**Comment by jeremyjh** [comment]
@asummers I think this is probably the only task remaining for a `1.0` release, do you agree?

**Comment by PragTob** [comment]
@jeremyjh I'm not @asummers but the bugs @aaronrenner opened after you commented this seem worth addressing before. Then again, there's always time for a 1.0.1 :) Thanks for all the work :tada:

**Comment by jeremyjh** [comment]
@PragTob Yes, definitely #314 needs to be fixed, and probably both are easy fixes so should just be done. I'm mostly concerned about backwards-incompatibility at this point, but that extends to warning filtering.

**Comment by asummers** [comment]
I'll do another quick language audit this weekend but once those bugs are fixed, I think we should be good to go. I can't think of anything else we need offhand.

**Comment by asummers** [comment]
Hey @jeremyjh heads up -- going through some of the messaging, and, there's some issues. Fixing them, but not completely done yet.

**Comment by jeremyjh** [comment]
Resolved in 4fb7a58b3b72780b7cafc33c71908ccfc1d85046
