### ISSUE TITLE
Result.Object.t/0 ?

### ISSUE THREAD

**Issue by ratbag98** [jeremyjh/dialyxir#306]
### Environment

```bash
elixir -v                     
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [hipe]

Elixir 1.7.4 (compiled with Erlang/OTP 21)

cat mix.lock | grep dialyxir  
  "dialyxir": {:hex, :dialyxir, "1.0.0-rc.5", "c9c2379c59cf2dfc74690f48866e33ffb55ff660e5e02405c14614d204efdc4f", [:mix], [{:erlex, "~> 0.2.1", [hex: :erlex, repo: "hexpm", optional: false]}], "hexpm"},
```

mix.exs project settings:

```
dialyzer: [
        plt_add_deps: :transitive,
        plt_add_apps: [:mix],
        ignore_warnings: ".dialyzer_ignore.exs",
        flags: [:unmatched_returns, :error_handling, :race_conditions, :no_opaque]
      ]
```

.dialyzer_ignore.exs contents:

```elixir
[
  ~r/unknown_function.*__impl__.*/,
  {"apps/myapp/lib/myapp/cldr.ex", :contract_supertype},
  {"apps/myapp/lib/myapp/cldr.ex", :extra_range},
  {"apps/otherapp/lib/otherapp/tickets.ex", :race_condition}
]
```

(app names changed to protect the guilty)

### Current behavior

Umbrella project. Running `mix dialyzer` returns (after the preamble):

```
done in 0m21.84s
:0:unknown_type
Unknown type: Result.Object.t/0.
________________________________________________________________________________
done (warnings were emitted)
```

The word "Result" doesn't appear anywhere in my code. Only occurrence is in deps (postgrex refers to Postgrex.Result.t().

Question, therefore, where is this error coming from? Is there a magic flag to provide more context?

### Expected behavior

No warning about `Result.Object.t/0`.

**Comment by asummers** [comment]
Dialyzer is unfortunately really petty about what information it gives there. It just gives us the unknown type and then drops any helpful context before we can look at it. I would go the other way around and search for any places you reference `Object`. Worth a shot but I'm assuming this code isn't public anywhere?

**Comment by ratbag98** [comment]
Not public, but your suggestion actually hit the spot - Absinthe uses Result.Object.t() - I'll get on to Ben about it.

**Comment by asummers** [comment]
Great! Since we can't really do much better with the current state of Dialyzer itself (believe me, I wish we could), I'm going to close this.
