### ISSUE TITLE
Inconsistent rules with mix format

### ISSUE THREAD

**Issue by reaysawa** [jeremyjh/dialyxir#308]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 21 [erts-10.2.3] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe]
Elixir 1.8.1 (compiled with Erlang/OTP 20)
```

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir):

`"dialyxir": {:hex, :dialyxir, "1.0.0-rc.4", "71b42f5ee1b7628f3e3a6565f4617dfb02d127a0499ab3e72750455e986df001", [:mix], [{:erlex, "~> 0.1", [hex: :erlex, repo: "hexpm", optional: false]}], "hexpm"}`

### Current behavior
```
    Agent.update(__MODULE__, fn state ->
      Map.update!(
        state,
        :some_bool_key,
        &true
      )
    end)
```

**IF I wrap the closure with &(true), the error seems to go away.**

However, mix format will automatically strip the parenthesis around non-argument-consuming lambdas like that, resulting in the following warning **after** mix format is ran:

```
invalid args for &, expected an expression in the format of &Mo
d.fun/arity, &local/arity or a capture containing at least one argument as &1, got: true
```

The only other choice is to use the fully verbose lambda syntax `fn _ -> true end`.

### Expected behavior
Dialyxir should comply with the stylistic formatting from mix format.

**Comment by asummers** [comment]
Where is `Dialyxir` complaining exactly? It seems like that error isn't from `Dialyxir` itself but I might be totally misunderstanding! `Dialyxir` doesn't really know how to look at the actual code itself but the error messages that Dialyzer itself spits out; if it were yelling at you about a suggested `@spec`, for example, I would completely understand. Can you throw together a small example and throw onto GitHub so I can play with it? 

I get a legitimate compiler error there when I try similar syntax in IEx, for whatever that's worth
```
iex(1)> Enum.map(1..10, &true) 
** (CompileError) iex:1: invalid args for &, expected an expression in the format of &Mod.fun/arity, &local/arity or a capture containing at least one argument as &1, got: true
iex(1)> Enum.map(1..10, &(true))
** (CompileError) iex:1: invalid args for &, expected an expression in the format of &Mod.fun/arity, &local/arity or a capture containing at least one argument as &1, got: true
    (stdlib) lists.erl:1354: :lists.mapfoldl/3
    (stdlib) lists.erl:1355: :lists.mapfoldl/3
```

**Comment by reaysawa** [comment]
Ah, I see! So it's indeed invalid syntax.

I'm used to formatters failing to work at all when there are syntax issues, but it seems like mix format is somehow overlooking this case. Since mix format was able to format the whole document regardless of the error, I thought Dyalixyr was the culprit for not understanding it.

My bad. Closing!
