### ISSUE TITLE
Can't ignore error in `1.0.0-rc.5`

### ISSUE THREAD

**Issue by rodrigues** [jeremyjh/dialyxir#310]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 21 [erts-10.3.1] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtr
ace]                                                                                            

Elixir 1.8.1 (compiled with Erlang/OTP 21)
```

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir):

`"dialyxir": {:hex, :dialyxir, "1.0.0-rc.5", "c9c2379c59cf2dfc74690f48866e33ffb55ff660e5e02405c1
4614d204efdc4f", [:mix], [{:erlex, "~> 0.2.1", [hex: :erlex, repo: "hexpm", optional: false]}], "
hexpm"}`

### Current behavior

Using absinthe brings some dialyzer errors I ignore in `.dialyzer_ignore.exs`.

After rc5, one of these warnings can't be anymore be ignored.

```
:0:unknown_type
Unknown type: Result.Object.t/0.
```

### Expected behavior

This line made the error to be ignored in rc4, it doesn't anymore:

`~r/Unknown type: Result\.Object\.t\/0/,`

It also didn't work:

`{":0: Unknown type 'Elixir.Result.Object':t/0"}`

**Comment by asummers** [comment]
That seems less than ideal! Which version did you bump from? Can you paste the `dialyzer` section of your `mix.exs`?

**Comment by rodrigues** [comment]
I was at rc.4 before.

**Comment by jeremyjh** [comment]
Some of the short warnings were modified, for example we strip `Elixir` off module names. To see the exact text you would need to ignore you can run `mix dialyzer --format short`.

**Comment by rodrigues** [comment]
@jeremyjh it works if I use the short format, but that's too generic for me to add to the ignore list:

```elixir
{":0:unknown_type Unknown type: t."},
```

**Comment by jeremyjh** [comment]
Agreed, thats a bug.

**Comment by jeremyjh** [comment]
I published the fix for this in an rc.6.

**Comment by rodrigues** [comment]
@jeremyjh now it works, thanks!
