### ISSUE TITLE
list_unused_filters: true in mix.exs doesn't cause --halt-exit-status to fail

### ISSUE THREAD

**Issue by aaronrenner** [jeremyjh/dialyxir#313]
When setting `list_unused_filters: true` via `mix.exs` and subsequently running `mix dialyzer --halt-exit-status`, it causes the number of "Unnessecary skips" to be output, but doesn't fail the build.

```
$ mix dialyzer --halt-exit-status
Finding suitable PLTs
Checking PLT...
[:compiler, :elixir, :kernel, :logger, :stdlib]
PLT is up to date!
ignore_warnings: .dialyzer_ignore.exs

Starting Dialyzer
[
  check_plt: false,
  init_plt: '/Users/aaron/projects/dialyxir_issue/_build/dev/dialyxir_erlang-21.3.2_elixir-1.8.1_deps-dev.plt',
  files_rec: ['/Users/aaron/projects/dialyxir_issue/_build/dev/lib/dialyxir_issue/ebin'],
  warnings: [:unknown]
]
Total errors: 2, Skipped: 2, Unnecessary Skips: 1
done in 0m1.27s
done (passed successfully)
```

Instead, if I want the build to fail, I have to add the command line option `--list-unused-filters`.
```
$ mix dialyzer --list-unused-filters --halt-exit-status
Finding suitable PLTs
Checking PLT...
[:compiler, :elixir, :kernel, :logger, :stdlib]
PLT is up to date!
ignore_warnings: .dialyzer_ignore.exs

Starting Dialyzer
[
  check_plt: false,
  init_plt: '/Users/aaron/projects/dialyxir_issue/_build/dev/dialyxir_erlang-21.3.2_elixir-1.8.1_deps-dev.plt',
  files_rec: ['/Users/aaron/projects/dialyxir_issue/_build/dev/lib/dialyxir_issue/ebin'],
  warnings: [:unknown]
]
Total errors: 2, Skipped: 2, Unnecessary Skips: 1
Unused filters:
{"lib/dialyxir_issue.ex"}
unused filters present
```

## Expected behavior

I would think that setting `list_unused_filters: true` in the mix config should be the same as setting the command line option `--list-unused-filters`. 

## Reproduction case

I've put together a sample app here: https://github.com/aaronrenner/dialyxir_issue. **You must this app run on Elixir 1.8.0 or 1.8.1 to trigger the dialyzer error, because it's related to [an issue in elixir](https://github.com/elixir-lang/elixir/pull/8841)**.

First run `mix dialyzer --halt-exit-status` and notice it doesn't fail as it should. 

Next run `mix dialyzer --list-unused-filters --halt-exit-status` and see that it fails as expected.

**Comment by asummers** [comment]
I buy that. Good catch. I bet that was frustrating to find.

**Comment by evnu** [comment]
I did some digging into this. In `Dialyxir.Project.list_unused_filters?/1` ([here](https://github.com/jeremyjh/dialyxir/blob/master/lib/dialyxir/project.ex#L159)), `:list_unused_filters` is always set in `args`. Then, the function never defaults to the configuration. The following would fix this:

```elixir
  defp list_unused_filters?(args) do
    # fetch!, as :list_unused_filters is always set at this point. It can be nil, though.
    Keyword.fetch!(args, :list_unused_filters) || dialyzer_config()[:list_unused_filters]
  end
```

`list_unused_filters` is always set in `Mix.Tasks.Dialyzer.run/1`:

```elixir
    args = [
      {:check_plt, opts[:force_check] || false},
      {:init_plt, String.to_charlist(Project.plt_file())},
      {:files_rec, Project.dialyzer_paths()},
      {:warnings, dialyzer_warnings(dargs)},
      {:format, opts[:format]},
      {:raw, opts[:raw]},
      {:list_unused_filters, opts[:list_unused_filters]}, # <<<< ----
      {:halt_exit_status, opts[:halt_exit_status]}
    ]
```
