### ISSUE TITLE
Feedback Request: Make --halt-exit-status the default?

### ISSUE THREAD

**Issue by jeremyjh** [jeremyjh/dialyxir#315]
I wish I'd opened this earlier, but my intention is to try not to have any breaking changes after 1.0, and lately I've been thinking we really have the wrong default around `--halt-exit-status` and this is our last chance to address it. With good dialyzer support in ElixirLS that can perform incremental analysis and provide results in the editor, I think one of the most important use cases remaining for `dialyxir` is to run analysis in CI and we have the wrong default for that.

Command line usage is important too, but there is no harm in exiting with non-zero there that I can think of. The only reason we didn't make it the default to begin with is I thought some people might be using dialyxir in mix-watch or similar, and didn't want to break them by terminating the VM.  Still, that would be a pretty obvious issue,  that would happen after upgrading dialyxir, and we can support `--watch` CLI arg and config entries to enable those use-cases.

I'd prefer new users not setup a CI pipeline and only find out it isn't working weeks later when lots of errors have built up, which could easily happen since you'd have a clean run to start with, you may not realize a failure isn't failing CI.

I think we will not warn if the `--halt-exit-status` *is* provided unnecessarily; one feature we'd support is setting `watch` in your mix.exs and then overriding with the CLI arg.

Please respond with your +/- or comment and let me know of any other considerations I'm missing.

**Comment by asummers** [comment]
I think we should message about the removal of the flag. One of the more annoying things is when libraries drop opts but don't tell me as a user of the library; the amount of stale opts in my `config.exs` and friends is maddening. I'm already in the "I'm bumping Dialyzer" mindset so doing that one extra task doesn't seem bad to me. 

The cheapest way to accomplish this is to drop support for `--halt-exit-status` and change the name to `--ignore-exit-status` and invert the behavior, I think. That should allow the watch case you were referring to.

**Comment by jeremyjh** [comment]
Ok. I was actually imagining a scenario where you want to ignore exit status by default (put the ignore flag in your `mix.exs`) but still have a way to halt on it at the CLI. That seems pretty unlikely though, I think you are right that a CLI option for `--ignore-exit-status` will be sufficient.

**Comment by axelson** [comment]
@jeremyjh I'm a little confused about the new default that you are proposing. Are you proposing that `mix dialyzer` will now halt by default on the first error that it encounters? (I believe I understand the other bit about the error status).

**Comment by jeremyjh** [comment]
@axelson Well, it will report all the errors, not just the first one. In order to return an error status you call `:erlang.halt` but we do this after error reporting. This is what it does when you run `mix dialyzer --halt-exit-status`. The default behavior is just print all the errors and normally the VM exits anyway since the task is finished. But if you've chained a task with `mix do` or are running from IEX or something, it would halt the VM out from under you.

**Comment by axelson** [comment]
Hmmm, the early halting seems like it could be slightly unexpected as a default (although you wouldn't hit that case that often). But if an error message was printed along with the halting I think that would help avoid someone trying to understand why there `mix do` command is not finishing.
