### ISSUE TITLE
Proposal: Warning examples (when they exist) as moduledocs?

### ISSUE THREAD

**Issue by asummers** [jeremyjh/dialyxir#329]
To improve HexDocs documentation, I propose using the example text as the `@moduledoc`, and then the example can reference `@moduledoc` instead. 

E.g.

```elixir
defmodule MyWarning do
  @moduledoc """
  This warning happens when you do ...

  Example:
  Blah blah
  """
  ...

  def explain() do
    @moduledoc 
  end
end
```

**Comment by jeremyjh** [comment]
I think it is a good idea. Would it make sense for explain to include a URL pointing at the hexdocs? Or maybe even the normal long form error could link to that.

**Comment by asummers** [comment]
If you're already seeing the explanation, I don't see a _ton_ of value linking externally. I could see some value from the long form linking outward though or instructing the user on how to get the explanation internally.

**Comment by jeremyjh** [comment]
Yeah I guess we shouldn't link from explain as its exactly the same information.
