### ISSUE TITLE
Pass dialyzer exit status on to mix

### ISSUE THREAD

**Issue by schnittchen** [jeremyjh/dialyxir#33]
It would be nice to have access to the exit status of the dialyzer run, to have the benefit of using mix for it in CI (or any scripted environment).

**Comment by jeremyjh** [comment]
When you say have the exit status, you mean have Mix exit with the same status code as returned by dialyzer?

I could not find any support for this in the Mix API. 

I confirmed I can call :erlang.halt with the return code from dialyzer but this would break things like mix command chaining. Still, I do not see why this couldn't be enabled with an option you pass, e.g.

`mix dialyzer --halt-exit-status`

Would that work for you?

**Comment by schnittchen** [comment]
Yes that would work. Alternatively, a mix task outputting the exact dialyzer command line would work as well (and be potentially more useful in the future).

**Comment by jeremyjh** [comment]
You mean just have it print the dialyzer command to stdout without invoking it? That would be easy enough. What do you mean by parse-able fashion though?

**Comment by schnittchen** [comment]
Would something like

```
DIALYZER_COMMAND=`mix dialyzer --print-command`
$DIALYZER_COMMAND
```

be possible? Might pose escaping problems, but that's the general idea.

**Comment by schnittchen** [comment]
The --halt-exit-status way was easy enough :)
