### ISSUE TITLE
Unknown warning: :map_update

### ISSUE THREAD

**Issue by space-pope** [jeremyjh/dialyxir#331]
### Environment

* Elixir 1.8.1/OTP 21

* Dialyxir 1.0.0-rc.6

### Current behavior
Reports the following error during analysis:
```
Unknown warning:
    :map_update


    Legacy warning:
    <module name>.ex:106: A key of type '<key_name>' cannot exist in a map of type #{'duration':=integer(), 'id':=_, 'title':=_, ...}
```

I redacted some keys and the name of the module since this seems like a pretty generic error. The spec was missing the key in question, and it looks like dialyxir just had a problem parsing the dialyzer error.

**Comment by jeremyjh** [comment]
This is fixed on master, in cdeb97c28893f4d5b912aca1c49b99a0b9b96d77.
