### ISSUE TITLE
Opaque type pattern matching disallowed

### ISSUE THREAD

**Issue by Fire-Dragon-DoL** [jeremyjh/dialyxir#339]
### Environment

```
$ elixir --version
Erlang/OTP 22 [erts-10.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.8.2 (compiled with Erlang/OTP 22)
$ cat mix.lock | grep dialyxir
  "dialyxir": {:hex, :dialyxir, "1.0.0-rc.6", "78e97d9c0ff1b5521dd68041193891aebebce52fc3b93463c0a6806874557d7d", [:mix], [{:erlex, "~> 0.2.1", [hex: :erlex, repo: "hexpm", optional: false]}], "hexpm"},
```

### Current behavior

When `dialyzer` task is executed, pattern matching against MapSet is considered an error. This line of code:

```elixir
@spec foo(set :: MapSet.t() :: MapSet.t()
def foo(%MapSet{} = set) do
  IO.inspect(set)
end

foo(MapSet.new())
```

Reports the following error:

```
lib/hello.ex:4:opaque_match
Attempted to pattern match against the internal structure of an opaque term.

Type:
MapSet.t(_)

Pattern:
%MapSet{}

This breaks the opaqueness of the term.
```

### Expected behavior

I'd expect `dialyxir` to report the error breaking `opaque` term only in situations where pattern matching with fields included (fields are supposed to be internal):

So this case should **report error**:

```elixir
%MapSet{map: _} = MapSet.new()
```

But this one should not:

```elixir
%MapSet{} = MapSet.new()
```

Otherwise opaque types behave like private types except they are visible in documentation.
In the [official elixir documentation it's clearly stated that you can pattern match against the empty struct but not it's internal fields](https://hexdocs.pm/elixir/MapSet.html).
I'd expect `dialyxir` to match the official Elixir documentation.

**Comment by jeremyjh** [comment]
Unfortunately this cannot be fixed in ‘dialyxir’. When you pattern match an empty struct you are indeed matching on its __struct__ member. This would need to be addressed in Elixir or in dialyzer. Somewhat related is the wontfix https://github.com/elixir-lang/elixir/pull/8480 .

**Comment by Fire-Dragon-DoL** [comment]
Based on a discussion on the Elixir slack, looks like my interpretation of `@opaque` is probably flawed. I thought as `@opaque` as hiding the content of a struct, but it's actually hiding even the fact that **it's a struct**.

Thanks @jeremyjh , you answered while I was typing and closing.
It should be fixed in the docs probably
