### ISSUE TITLE
MatchError

### ISSUE THREAD

**Issue by RichMorin** [jeremyjh/dialyxir#343]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):

    Elixir 1.9.0 (compiled with Erlang/OTP 22)

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir):

    "dialyxir": {:hex, :dialyxir, "1.0.0-rc.6",
    "78e97d9c0ff1b5521dd68041193891aebebce52fc3b93463c0a6806874557d7d",
    [:mix], [{:erlex, "~> 0.2.1", [hex: :erlex, repo: "hexpm", optional: false]}], "hexpm"},

### Current behavior

    ** (MatchError) no match of right hand side value: {:error, {1, :erl_parse,
      ['syntax error before: ', '\'::\'']}}
        dialyzer.erl:626: anonymous fn/1 in :dialyzer.sig/2
        dialyzer.erl:541: :dialyzer.call_or_apply_to_string/6
        dialyzer.erl:322: :dialyzer.message_to_string/2
        dialyzer.erl:297: :dialyzer.format_warning/2
        lib/dialyxir/formatter.ex:106: Dialyxir.Formatter.format_warning/2
        lib/dialyxir/formatter.ex:275: anonymous fn/2
          in Dialyxir.Formatter.filter_legacy_warnings/2
        (elixir) lib/enum.ex:3029: Enum.reject_list/2
        (elixir) lib/enum.ex:3032: Enum.reject_list/2
        lib/dialyxir/formatter.ex:32: Dialyxir.Formatter.format_and_filter/4
        lib/dialyxir/dialyzer.ex:47: Dialyxir.Dialyzer.Runner.run/2
        lib/dialyxir/dialyzer.ex:74: Dialyxir.Dialyzer.dialyze/3
        lib/mix/tasks/dialyzer.ex:263: Mix.Tasks.Dialyzer.run_dialyzer/2
        lib/mix/tasks/dialyzer.ex:195: Mix.Tasks.Dialyzer.run/1
        (mix) lib/mix/task.ex:331: Mix.Task.run_task/3
        (mix) lib/mix/cli.ex:79: Mix.CLI.run_task/2

### Expected behavior

    (some kind of formatted diagnostic)

### Discussion

I pushed a snapshot (469fb36) of my code base to `https://github.com/RichMorin/PA_all`.

**Comment by jeremyjh** [comment]
Hi, can you try upgrading to Erlang 22.0.5?

https://github.com/jeremyjh/dialyxir/issues/341

**Comment by RichMorin** [comment]
> Hi, can you try upgrading to Erlang 22.0.5?

Sure!  After a bit of investigation, I ran "brew upgrade erlang" and
upgraded from 22.0.4 to 22.0.5.  Incidentally, it seems odd that the
"elixir -v" and even "erl -v" only say that I'm running "Erlang/OTP 22".

Anyway, I then re-ran "mix dialyzer --quiet".  After the (expected) long
wait, it successfully printed out my diagnostics.  Thanks!

-r
