### ISSUE TITLE
improving the "breaks the contract" output

### ISSUE THREAD

**Issue by RichMorin** [jeremyjh/dialyxir#346]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):

    Elixir 1.9.0 (compiled with Erlang/OTP 22)

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir):

    "dialyxir": {:hex, :dialyxir, "1.0.0-rc.6",
    "78e97d9c0ff1b5521dd68041193891aebebce52fc3b93463c0a6806874557d7d",
    [:mix], [{:erlex, "~> 0.2.1", [hex: :erlex, repo: "hexpm", optional: false]}], "hexpm"},

### Current behavior

A couple of my specs look like this:

    @spec emit_toml(s, s, map) :: s when s: String.t
    @spec add_kv_info(km, map, atom) :: km when km: ITT.kv_map

Dialyxir's "breaks the contract" messages look like this:

    (115, 115, map()) :: 115 when s: String.t()
    (:km, map(), atom()) :: :km when km: InfoToml.Types.kv_map()

In the first case, it's printing the decimal value (115) of the character "s". In the second, it's printing `km` as the atom `:km`. Neither is correct.

### Expected behavior

    (s, s, map()) :: s when s: String.t()
    (km, map(), atom()) :: km when km: InfoToml.Types.kv_map()

### Discussion

I realize that there is some ambiguity between atoms, strings, and lists of integers. However, I'm hoping that Dialyxzir can handle this more gracefully.

**Comment by jeremyjh** [comment]
Sorry, just re-read this - I'd forgotten there were two issues. I think the first issue with the char codes is fixed, if you want to try Erlex master @RichMorin. Re-opening for the second issue with formatting type variables in the arg as an atom, which is definitely not as easy to solve.

**Comment by rodrigues** [comment]
confirmed issue with char codes is fixed 👍🏼

**Comment by asummers** [comment]
This is fixed in Erlex 0.2.4 (thanks to @jeremyjh)
