### ISSUE TITLE
play nicely with dialyzex?

### ISSUE THREAD

**Issue by RichMorin** [jeremyjh/dialyxir#348]
I've been using Dialyxir intensively for a while, but I'd like to give Dialyzex a try. Sadly, when I try to add them both as dependencies, all sorts of breakage ensue. Please try to find a way to let users install and use both of these packages. (See also: https://github.com/Comcast/dialyzex/issues/17)

**Comment by jeremyjh** [comment]
I don't think it is possible without changing the command name, which would cause lots more breakage for people.

**Comment by asummers** [comment]
What would be the point of having both? They're both pretty printing the same errors, so either you like one or the other. Dialyxir allows you to print the original dialyzer messages with `mix dialyzer --format dialyzer`, and Dialyzex does not do any pretty printing, so they should be the same output with that flag.

**Comment by RichMorin** [comment]
Dialyzex claims to provide several features which Dialyxir does not; see the [readme](https://hexdocs.pm/dialyzex/readme.html) for details. There is also the possibility that it (or some other package) will offer additional features in the future. So, an interested user might wish to try out various Dialyzer wrappers, in order to compare their feature sets. S/he could then decide which one(s) to use, post issues or patches, etc.

The real problem, IMHO, is that both Dialyzex and Dialyxir are trashing the mix and module name spaces, taking over names (e.g., [Dd]ialyzer) that don't belong to them. That ship has sailed, unfortunately, but maybe the authors can figure out a way to straighten things out.

**Comment by OvermindDL1** [comment]
> Dialyzex claims to provide several features which Dialyxir does not; see the readme for details.

I'm curious what those are?  Your link doesn't seem to state any of such features?

**Comment by RichMorin** [comment]
Because of the name space conflicts (and my own laziness), I haven't actually tried Dialyzex. So, I'll take your word that it doesn't really provide any added value. I also agree that Dialyzex doesn't appear to be very active. So, I'll close the issue.
