### ISSUE TITLE
Bad format: char misrepresented as int on typespec argument

### ISSUE THREAD

**Issue by rodrigues** [jeremyjh/dialyxir#349]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):

```
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:4:4] [ds:4:4:10] [async-threads:1] [hipe] [dtrace]

Elixir 1.9.0 (compiled with Erlang/OTP 22)
```

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir):

```
dialyxir       1.0.0-rc.6
erlex          0.2.2
```
### Current behavior

Not sure if this is an issue of dialyxir or erlex:

When I run `mix dialyzer`, some errors were showing a mysterious `97` and `98`:

```elixir
lib/stream_data.ex:1425:contract_subtype
Type specification is a subtype of the success typing.

Function:
StreamData.tree/2

Type specification:
@spec tree(input(97), (child_data :: t(97 | 98) -> t(98))) :: t(97 | 98) when a: term(), b: term()

Success typing:
@spec tree(_, _) :: %StreamData{:generator => (_, _ -> map())}
```

### Expected behavior

These are actually `a` and `b` char values. So something must be off with the formatter. The `--format raw` outputs it fine:

```elixir
{:warn_contract_subtype, {'lib/stream_data.ex', 1425},
{:contract_subtype, [StreamData, :tree, 2,
'(input(a),fun((child_data::t(a | b)) -> t(b))) -> t(a | b) when a :: term(), b :: term()', '(_,_) -> \#{\'__struct__\':=\'Elixir.StreamData\', \'generator\':=fun((_,_) -> map())}']}}
```

**Comment by RichMorin** [comment]
I think this is one of the problems I reported in https://github.com/jeremyjh/dialyxir/issues/346

**Comment by rodrigues** [comment]
@RichMorin indeed, didn't see it, thanks!

**Comment by jeremyjh** [comment]
This should be fixed if you do a `mix deps.update erlex`.
