### ISSUE TITLE
Failed to format warning - Legacy warning (1.0.0 rc7)

### ISSUE THREAD

**Issue by sphaso** [jeremyjh/dialyxir#366]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):

```
Erlang/OTP 21 [erts-10.2.5] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.7.4 (compiled with Erlang/OTP 21)
```

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir):

` "dialyxir": {:hex, :dialyxir, "1.0.0-rc.7", "6287f8f2cb45df8584317a4be1075b8c9b8a69de8eeb82b4d9e6c761cf2664cd", [:mix], [{:erlex, ">= 0.2.5", [hex: :erlex, repo: "hexpm", optional: false]}], "hexpm"},`

### Current behavior

```
Failed to format warning:
"@spec a:insurance_code :: :ok\ndef a() do\n  :ok\nend\n"


Legacy warning:
lib/finance/bridge/netsuite/adapter.ex:400: Guard test _k@1::<<_:64,_:_*8>> =:= 'insurance_code' can never succeed
```
the whereabouts of line 400:

```
  @spec transform_key({atom() | String.t(), any()}) :: {any(), any()}
  defp transform_key({k, v})
       when k in [
              :insurance_code,
              :vehicle_type,
              :underwriting_year,
              :instalment_net_premium,
              :instalment_gross_premium,
              :action_type
            ] do
    {String.to_atom("custcol_gn_" <> Atom.to_string(k)), v}
  end

  defp transform_key({k, v}), do: {k, v}
```

Let me know if I can help with further tests \ investigation. Thanks!

**Comment by jeremyjh** [comment]
Hi, can you run `mix dialyzer --format raw` please?

**Comment by sphaso** [comment]
Hi @jeremyjh !
this is the result:
`{:warn_matching, {'lib/finance/bridge/netsuite/adapter.ex', 400}, {:guard_fail, ['_k@1::<<_:64,_:_*8>>', '=:=', '\'insurance_code\'']}}`
