### ISSUE TITLE
Unknown error occurred with Dialyxir.Warnings.OpaqueGuard.format_long/1

### ISSUE THREAD

**Issue by losvedir** [jeremyjh/dialyxir#376]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): Elixir 1.9.4, Erlang/OTP 22.1.7

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir): 1.0.0-rc.7

### Current behavior
 * Describe current behavior. Include errors, stack traces, and any additional information that might be important here.

Filing this ticket because the error message asked me to. I glanced through the recent issues but didn't see it already. Apologies if I missed it.

Output is:

```
Total errors: 1, Skipped: 0, Unnecessary Skips: 0
done in 0m1.98s
Please file a bug in https://github.com/jeremyjh/dialyxir/issues with this message.

Unknown error occurred: %FunctionClauseError{args: nil, arity: 1, clauses: nil, function: :format_long, kind: nil, module: Dialyxir.Warnings.OpaqueGuard}


Legacy warning:
lib/engine/predictions.ex:68: Guard test __@1::'nil' | 'Elixir.MapSet':t(binary()) =:= 'false' contains an opaque term as 1st argument
________________________________________________________________________________
done (warnings were emitted)
Halting VM with exit status 2
```

The output of `mix dialyzer --format raw` is:

```
{:warn_opaque, {'lib/engine/predictions.ex', 68}, {:opaque_guard, ['__@1::\'nil\' | \'Elixir.MapSet\':t(binary())', '=:=', '\'false\'', [1]]}}
```

**Comment by asummers** [comment]
Sorry for the SUPER long delay. Do you happen to have the live example that caused this? I have been unable to make this happen in any of my test cases and I'd like to have a live example to play with in the explanation section and be able to solve your bug =).

**Comment by losvedir** [comment]
Sorry, I don't really remember and can't seem to reproduce now. Looking back in that code base for commits around the date I opened this issue it seems to be from when we upgraded from Elixir 1.6 / Erlang 20 to Elixir 1.9 / Erlang 22. I don't see any particular commits that look like workarounds or fixes, and it's passing now without errors, so perhaps it was just cached compiled artifacts or something. I'll close the PR because the bug isn't affecting us anymore, but feel free to re-open if you want.
