### ISSUE TITLE
Failed to format warning: @spec a:none | ...

### ISSUE THREAD

**Issue by lukaszsamson** [jeremyjh/dialyxir#378]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
Erlang/OTP 22 [erts-10.6] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]
Elixir 1.9.4 (compiled with Erlang/OTP 22)
* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir):
master @ 62310a9cbcbb88a9ec08061d93946bf0f096bbbc
### Current behavior
```
Failed to format warning:
"@spec a:none | %{:active_param => pos_integer(), :signatures => [%{:name => binary(), :params => [binary()]}]}\ndef a() do\n  :ok\nend\n"


Legacy warning:
lib/elixir_sense/providers/signature.ex:18: The success typing for 'Elixir.ElixirSense.Providers.Signature':find/3 implies that the function might also return #{'active_param':=non_neg_integer(), 'pipe_before':=boolean(), 'signatures':=maybe_improper_list()} but the specification return is 'none' | #{'active_param':=pos_integer(), 'signatures':=[#{'name':=binary(), 'params':=[binary()]}]}
```

**Comment by asummers** [comment]
You have code in the wild that does that? Awesome! Would you mind giving me an example so I can improve the docs?

**Comment by lukaszsamson** [comment]
@asummers to reproduce
1. clone https://github.com/elixir-lsp/elixir_sense
2. in `mix.exs` add `:overspecs` dialyzer flag
3. (optional ) bump dialyxir to github master
4. mix deps.get && mix dialyzer
