### ISSUE TITLE
1.0 stable release? 🙂

### ISSUE THREAD

**Issue by rodrigues** [jeremyjh/dialyxir#379]
I've been [asked](https://github.com/alfert/propcheck/pull/143#discussion_r365419173) today about current dialyxir not being "stable" yet, and just saw that `rc.7` is actually a few months old, without any issues for me in many projects.

I know there are issues opened, so not sure what you would like to resolve before hitting the 1.0 mark.

Please feel free to close this, as it's more of a question, just relaying the demand, and interested to know about your plans about this 🙂

Thanks for the good work!

**Comment by jeremyjh** [comment]
Yeah, there isn't much left to do to get to a stable release, I just kind of ran out of steam and been busy with work and other pursuits. It won't change much but I know it does raise questions in down-streams that are totally reasonable so I'll try to get back to it this week.

**Comment by asummers** [comment]
I think we should just go to battle with it. It's time.

**Comment by asummers** [comment]
We should change the minimum Erlex version to `>= 0.2.6` so we ensure folks get up to date  versions, but that's the only thing on my short list.

**Comment by asummers** [comment]
I created a branch to get that ball rolling. Feel free to push anything you'd like to it @jeremyjh 

https://github.com/jeremyjh/dialyxir/compare/release-1-0

**Comment by jeremyjh** [comment]
@asummers I added just one change from the milestone list in #386. I think thats all thats really needed for a hex release 1.0 though I should still plan to create a CHANGELOG

**Comment by jeremyjh** [comment]
[1.0.0](https://hex.pm/packages/dialyxir/1.0.0) pushed to Hex.
