### ISSUE TITLE
Filterer should not assume Erlex success

### ISSUE THREAD

**Issue by asummers** [jeremyjh/dialyxir#383]
### Environment

* Elixir & Erlang/OTP versions (elixir --version): 
```
Erlang/OTP 22 [erts-10.4.4] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe]

Elixir 1.10.0 (compiled with Erlang/OTP 21)
```

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir): rc7
 
### Current behavior
See discussion in https://elixirforum.com/t/dialyzer-issue-with-phoenix-1-4-15/29687

`Dialyxir.Formatter.filter_warning/3` calls `format_warning(warning, :short)` which assumes Erlex will parse appropriately. This is not true. 

### Expected behavior
This code is resilient to the short formatting failing.

**Comment by anthonator** [comment]
Just to note, this is popping up due to upgrading Phoenix from 1.4.14 to 1.4.15. So I imagine this will affect a lot of projects.

**Comment by k-cross** [comment]
Yes, we are also affected here.
