### ISSUE TITLE
Unknown functions

### ISSUE THREAD

**Issue by hojgr** [jeremyjh/dialyxir#41]
Hello,

I've tried to use Dialyxir and it works I think (I see errors/warning about my project.)

But under analysis of my project there is
```
Unknown functions:
  'Elixir.Calendar.DateTime':'advance!'/2
  'Elixir.Calendar.DateTime':now_utc/0
  'Elixir.Ecto':build_assoc/2
  'Elixir.Ecto.Adapters.Postgres':rollback/2
  'Elixir.Ecto.Adapters.Postgres':stop/3
  'Elixir.Ecto.Adapters.Postgres':transaction/3
  'Elixir.Ecto.Changeset':cast/4
  'Elixir.Ecto.Changeset':get_change/2
```
The list goes on.

I've googled around and found I have to add the deps to `dialyzer: path`. After adding `ecto` and `plug` and running `mix dialyzer`, it eats all of my remaining memory (7GB) and then keeps eating away swap. I've stopped it when it took 9GB.

It even eats all of my memory when I add just `ecto`.

I added it in mix.exs like this
```
   dialyzer: [
    paths: [
      "_build/dev/lib/ecto/ebin"
    ]
  ]
```

Am I doing it wrong or is it normal that it eats 9GB memory for my small project?

Thanks

**Comment by jeremyjh** [comment]
I assume it would be dialyzer using the memory but I do not know why it would do that. 

Probably it would be better to add your dependencies to the plt, using plt_add_deps and then rerun mix dialyzer.plt.
