### ISSUE TITLE
mix dialyzer.plt not working

### ISSUE THREAD

**Issue by fourcube** [jeremyjh/dialyxir#42]
Hi there,

I'm trying to run `mix dialyzer.plt` with dialyxir 0.3.3 on OSX El Capitan. Elixir and OTP Versions:

```
Erlang/OTP 18 [erts-7.2.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]
Elixir 1.2.2
Mix 1.2.2
```
#### Result
```
$ mix dialyzer.plt
Starting PLT Core Build ... this will take awhile
dialyzer --output_plt /Users/CGR/.dialyxir_core_18_1.2.2.plt --build_plt --apps erts kernel stdlib crypto public_key -r /usr/local/Cellar/elixir/1.2.2/bin/../lib/elixir/../eex/ebin /usr/local/Cellar/elixir/1.2.2/bin/../lib/elixir/../elixir/ebin /usr/local/Cellar/elixir/1.2.2/bin/../lib/elixir/../ex_unit/ebin /usr/local/Cellar/elixir/1.2.2/bin/../lib/elixir/../iex/ebin /usr/local/Cellar/elixir/1.2.2/bin/../lib/elixir/../logger/ebin /usr/local/Cellar/elixir/1.2.2/bin/../lib/elixir/../mix/ebin

dialyzer: Could not get abstract code for file: /usr/local/Cellar/elixir/1.2.2/bin/../lib/elixir/../elixir/ebin/Elixir.String.Graphemes.beam (please recompile it with +debug_info)


** (FunctionClauseError) no function clause matching in Keyword.get/3
    (elixir) lib/keyword.ex:150: Keyword.get(:no_such_file, :files, nil)
    lib/mix/tasks/dialyzer.plt.ex:142: Mix.Tasks.Dialyzer.Plt.core_plt_contains?/2
    lib/mix/tasks/dialyzer.plt.ex:133: anonymous fn/1 in Mix.Tasks.Dialyzer.Plt.missing_apps/0
    (elixir) lib/enum.ex:738: anonymous fn/3 in Enum.filter/2
    (elixir) lib/enum.ex:1473: Enum."-reduce/3-lists^foldl/2-0-"/3
    (elixir) lib/enum.ex:738: Enum.filter/2
    lib/mix/tasks/dialyzer.plt.ex:116: Mix.Tasks.Dialyzer.Plt.need_add?/0
    lib/mix/tasks/dialyzer.plt.ex:57: Mix.Tasks.Dialyzer.Plt.run/1

```

Could this be a problem with the brew package I have used to install elixir? I have tried to run `mix dialyzer.plt` in this repo: https://github.com/fourcube/metrics/tree/dialyxir_test

**Comment by fourcube** [comment]
I tried to find out if I could build elixir from source and specify the recommended `+debug_info` flag. Even though the available command-line flags to `elixirc`

```
$ bin/elixirc -h
Usage: elixirc [elixir switches] [compiler switches] [.ex files]

  -o               The directory to output compiled files
  --no-docs        Do not attach documentation to compiled modules
  --no-debug-info  Do not attach debug info to compiled modules
  --ignore-module-conflict
  --warnings-as-errors Treat warnings as errors and return non-zero exit code
  --verbose        Print informational messages.

** Options given after -- are passed down to the executed code
** Options can be passed to the erlang runtime using ELIXIR_ERL_OPTIONS
** Options can be passed to the erlang compiler using ERL_COMPILER_OPTIONS
```

hint that the source should always be compiled with debug_info, this doesn't seem to be the case. After I checked out the elixir source, I compiled it with

`ERL_COMPILER_OPTIONS=debug_info make`. `mix dialyzer.plt` executed successfully afterwards.

**Comment by jeremyjh** [comment]
So maybe the brew package was not compiled with that option?

**Comment by fourcube** [comment]
Thank you for your reply. I'll contact the maintainer of the brew package.

**Comment by vhf** [comment]
@fourcube any news from the brew package manager? I'm running into the exact same issue.

**Comment by vhf** [comment]
Update with more info: it seems it has nothing to do with Elixir's brew package manager, it's more of a problem with Elixir itself, cf elixir#4250 which is fixed in master.

**Comment by fourcube** [comment]
@vhf thank you for digging up the issue. So the manual compilation with the `ERL_COMPILER_OPTIONS=debug_info` did not have any effect at all... 

At the moment, cloning master / 1.2.2, running `make` and prepending `elixir/bin` to `$PATH` seems to be an easy workaround until the next release.
