### ISSUE TITLE
1.1 Release?

### ISSUE THREAD

**Issue by baseballlover723** [jeremyjh/dialyxir#423]
Is it possible to release a new version of dialyxir? It's been almost a year since the last release, and theres some new stuff on master.

**Comment by oliver-kriska** [comment]
fyi all changes https://github.com/jeremyjh/dialyxir/compare/1.0.0...master

**Comment by jeremyjh** [comment]
Hey, there really isn't much of importance that has changed, but yes I will cut a new release today or tomorrow.

**Comment by jeremyjh** [comment]
Hey, sorry for the long delay but 1.1 is now on Hex. See the [changelog](https://github.com/jeremyjh/dialyxir/blob/master/CHANGELOG.md#110---2021-02-18).
