### ISSUE TITLE
Any way to get filename for the `Unknown type` errors?

### ISSUE THREAD

**Issue by jisaacstone** [jeremyjh/dialyxir#426]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):

    Erlang/OTP 23 [erts-11.0.3] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [hipe] [dtrace]
    Elixir 1.10.4 (compiled with Erlang/OTP 23)

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir):

    "dialyxir": {:hex, :dialyxir, "1.0.0", "6a1fa629f7881a9f5aaf3a78f094b2a51a0357c843871b8bc98824e7342d00a5", [:mix], [{:erlex, ">= 0.2.6", [hex: :erlex, repo: "hexpm", optional: false]}], "hexpm", "aeb06588145fac14ca08d8061a142d52753dbc2cf7f0d00fc1013f53f8654654"},

### Current behavior
 * Describe current behavior. Include errors, stack traces, and any additional information that might be important here.

If I have a type in a `@spec`, but for get to alias, import, require, etc the module, the error message returned has no way to determine the file or line the error occurred on. This is a problem for example right now I got done with a refactor that touched ~30 files and I missed an alias __somewhere__, but I have no idea where.

### Expected behavior

* A short description of the expected behavior.
error message should have file name. Even better: line number

to reproduce

mix.exs
```elixir
defmodule Test.MixProject do
  use Mix.Project

  def project do
    [
      app: :test,
      version: "0.1.0",
      elixir: "~> 1.10",
      dialyzer: [
        flags: [:unmatched_returns, :error_handling, :race_conditions, :unknown],
      ],
      deps: deps()
    ]
  end

  def application, do: []

  defp deps do
    [{:dialyxir, "~> 1.0", only: [:dev], runtime: false}]
  end
end
```

lib/text.ex
```elixir
defmodule Test do
  @spec hello(arg: Foo.t) :: {Foo.t, atom}
  def hello(arg) do
    {arg, :world}
  end
end
```

```
$ mix dialyzer
Finding suitable PLTs
Checking PLT...
[:compiler, :elixir, :kernel, :logger, :stdlib]
PLT is up to date!
No :ignore_warnings opt specified in mix.exs and default does not exist.

Starting Dialyzer
[
  check_plt: false,
  init_plt: '/Users/larpy/game/test/_build/dev/dialyxir_erlang-23.0.3_elixir-1.10.4_deps-dev.plt',
  files: ['/Users/larpy/game/test/_build/dev/lib/test/ebin/Elixir.Test.beam'],
  warnings: [:unmatched_returns, :error_handling, :race_conditions, :unknown,
   ...]
]
Total errors: 1, Skipped: 0, Unnecessary Skips: 0
done in 0m1.21s
:0:unknown_type
Unknown type: Foo.t/0.
________________________________________________________________________________
done (warnings were emitted)
Halting VM with exit status 2
```

**Comment by asummers** [comment]
Any work here would have to be in `dialyzer.erl` in OTP itself. We forward what information we get faithfully, but dialyzer itself drops this at the door before it even gets to dialyxir. 

FWIW, I would be ecstatic with such an improvement upstream; this is one of the more annoying things to track down, particularly when retrofitting dialyzer onto an existing project.
