### ISSUE TITLE
Dialyxir plt_add_deps: true does not get nested dependencies

### ISSUE THREAD

**Issue by jlee0831** [jeremyjh/dialyxir#43]
It seems that the dependency list is built from the mix project dependencies (https://github.com/jeremyjh/dialyxir/blob/master/lib/mix/tasks/dialyzer.plt.ex#L97-L101).  However this does not include nested dependencies.  

It seems like it could get the full dependency list from the `mix.lock` file instead, but I'm not sure if this was a consideration that you may have already had.  Is there a reason it is not doing this currently?

**Comment by jeremyjh** [comment]
Why do you need a transitive dependency in the PLT? Really any module that
you directly call should have a deps entry in your own mix file. Loading
all transitive dependency by default sounds like overkill but I'd probably
take a PR that made it optional.

**Comment by jlee0831** [comment]
Perhaps I'm misunderstanding how to configure dialyxir properly, but I've built a sample app to demonstrate our issue here: https://github.com/jlee0831/sample-dialyxir-dependency-error-example.  The repository is a new phoenix app and you can see the output of both `mix dialyzer.plt` and `mix dialyzer` in the `README.md` of the sample repo.  But the short of it is that dialyzer complains about dependencies on both `plug` and `ecto`.

**Comment by jeremyjh** [comment]
The Phoenix project generator creates files that directly use the Ecto module, but does not include ecto as a dependency. It includes phoenix_ecto which pulls in Ecto transitively. But again, I do not think it is a good practice to rely on transitive dependencies to pull in code that you are using directly in your project. So the way I would recommend fixing this for your example, is to add ecto and plug to the deps in your mix.exs.

As I said I'm not against having a feature that would pull in transitive dependencies but it I'm quite sure it is not what people would expect it to do by default, so it would need to be opt-in.

**Comment by aaronjensen** [comment]
@chrismccord thoughts on this? It'd be nice to have dialyxir work w/ phoenix out of the box, should the generator add dependencies for all things it uses directly? It makes some sense, I think.

**Comment by ciastek** [comment]
Rebar [has it](https://github.com/erlang/rebar3/issues/778).

**Comment by jeremyjh** [comment]
Thanks @ciastek - that is a very relevant thread and fishcakez makes some great points about why we don't want to do this by default. If no one one submits a PR for a property to do this I will probably implement it at some point myself but I can't see myself using it.

**Comment by jeremyjh** [comment]
mix_add_deps :transitive provides this feature from 0.3.4, available on hex.pm

**Comment by slashmili** [comment]
I'm still facing unknown functions for `Elixir.Ecto.*` functions.

```
elixir --version
Erlang/OTP 19 [erts-8.1] [source] [64-bit] [smp:8:8] [async-threads:10] [hipe] [kernel-poll:false] [dtrace]

Elixir 1.3.3
```

```
diff --git a/mix.exs b/mix.exs
index e990f4b..c50992e 100644
--- a/mix.exs
+++ b/mix.exs
@@ -10,6 +10,7 @@ defmodule SeatSaver.Mixfile do
      build_embedded: Mix.env == :prod,
      start_permanent: Mix.env == :prod,
      aliases: aliases(),
+     dialyzer: [plt_add_deps: :transitive],
      deps: deps()]
   end
```

and this is my dependency list:
```
  defp deps do
    [{:phoenix, "~> 1.2.0"},
     {:phoenix_pubsub, "~> 1.0"},
     {:phoenix_ecto, "~> 3.0"},
     {:postgrex, ">= 0.0.0"},
     {:phoenix_html, "~> 2.6"},
     {:phoenix_live_reload, "~> 1.0", only: :dev},
     {:gettext, "~> 0.11"},
     {:cowboy, "~> 1.0"},
     {:dialyxir, "~> 0.3.5"}]
  end
```

**Comment by jeremyjh** [comment]
Milad can you paste the output of mix dialyzer.plt ?

**Comment by slashmili** [comment]
Sure, sorry I should have put it here!

This is output of `mix dialyzer.plt`: 

```
mix dialyzer.plt
Checking PLT for missing apps.
Checking PLT for updated apps.
dialyzer --check_plt --plt /Users/milad/.dialyxir_core_19_1.3.3.plt -pa _build/dev/lib/connection/ebin -pa _build/dev/lib/cowboy/ebin -pa _build/dev/lib/cowlib/ebin -pa _build/dev/lib/db_connection/ebin -pa _build/dev/lib/decimal/ebin -pa _build/dev/lib/dialyxir/ebin -pa _build/dev/lib/ecto/ebin -pa _build/dev/lib/fs/ebin -pa _build/dev/lib/gettext/ebin -pa _build/dev/lib/mime/ebin -pa _build/dev/lib/phoenix/ebin -pa _build/dev/lib/phoenix_ecto/ebin -pa _build/dev/lib/phoenix_html/ebin -pa _build/dev/lib/phoenix_live_reload/ebin -pa _build/dev/lib/phoenix_pubsub/ebin -pa _build/dev/lib/plug/ebin -pa _build/dev/lib/poison/ebin -pa _build/dev/lib/poolboy/ebin -pa _build/dev/lib/postgrex/ebin -pa _build/dev/lib/ranch/ebin --apps erts kernel stdlib crypto public_key connection cowboy cowlib db_connection decimal dialyxir ecto fs gettext mime phoenix phoenix_ecto phoenix_html phoenix_live_reload phoenix_pubsub plug poison poolboy postgrex ranch -r /usr/local/Cellar/elixir/1.3.3/bin/../lib/elixir/../eex/ebin /usr/local/Cellar/elixir/1.3.3/bin/../lib/elixir/../elixir/ebin /usr/local/Cellar/elixir/1.3.3/bin/../lib/elixir/../ex_unit/ebin /usr/local/Cellar/elixir/1.3.3/bin/../lib/elixir/../iex/ebin /usr/local/Cellar/elixir/1.3.3/bin/../lib/elixir/../logger/ebin /usr/local/Cellar/elixir/1.3.3/bin/../lib/elixir/../mix/ebin
  Checking whether the PLT /Users/milad/.dialyxir_core_19_1.3.3.plt is up-to-date... yes
done (passed successfully)
```

and this is output of `mix dialyzer` : 
```
mix dialyzer
Starting Dialyzer
dialyzer --no_check_plt --plt /Users/milad/.dialyxir_core_19_1.3.3.plt -Wunmatched_returns -Werror_handling -Wrace_conditions -Wunderspecs /private/tmp/seat_saver/_build/dev/lib/seat_saver/ebin
  Proceeding with analysis...
repo.ex:1: Callback info about the 'Elixir.Ecto.Repo' behaviour is not available
Unknown functions:
  'Elixir.Ecto.Adapters.Postgres':'in_transaction?'/1
  'Elixir.Ecto.Adapters.Postgres':rollback/2
  'Elixir.Ecto.Adapters.SQL':query/4
  'Elixir.Ecto.Adapters.SQL':'query!'/4
  'Elixir.Ecto.LogEntry':log/1
  'Elixir.Ecto.Repo.Preloader':preload/4
  'Elixir.Ecto.Repo.Queryable':aggregate/6
  'Elixir.Ecto.Repo.Queryable':all/4
  'Elixir.Ecto.Repo.Queryable':delete_all/4
  'Elixir.Ecto.Repo.Queryable':get/5
  'Elixir.Ecto.Repo.Queryable':'get!'/5
  'Elixir.Ecto.Repo.Queryable':get_by/5
  'Elixir.Ecto.Repo.Queryable':'get_by!'/5
  'Elixir.Ecto.Repo.Queryable':one/4
  'Elixir.Ecto.Repo.Queryable':'one!'/4
  'Elixir.Ecto.Repo.Queryable':transaction/4
  'Elixir.Ecto.Repo.Queryable':update_all/5
  'Elixir.Ecto.Repo.Schema':delete/4
  'Elixir.Ecto.Repo.Schema':'delete!'/4
  'Elixir.Ecto.Repo.Schema':insert/4
  'Elixir.Ecto.Repo.Schema':'insert!'/4
  'Elixir.Ecto.Repo.Schema':insert_all/5
  'Elixir.Ecto.Repo.Schema':insert_or_update/4
  'Elixir.Ecto.Repo.Schema':'insert_or_update!'/4
  'Elixir.Ecto.Repo.Schema':update/4
  'Elixir.Ecto.Repo.Schema':'update!'/4
  'Elixir.Ecto.Repo.Supervisor':config/3
  'Elixir.Ecto.Repo.Supervisor':start_link/4
 done in 0m2.06s
done (warnings were emitted)
```

**Comment by rozap** [comment]
@slashmili did you end up figuring this out? I'm seeing the same thing with a new phoenix app.

**Comment by slashmili** [comment]
@rozap No, it's still the same
