### ISSUE TITLE
Line numbers broken on 1.12 with erlang 24

### ISSUE THREAD

**Issue by michaelst** [jeremyjh/dialyxir#430]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 24 [erts-12.0.1] [source] [64-bit] [smp:12:12] [ds:12:12:10] [async-threads:1] [jit]
Elixir 1.12.1 (compiled with Erlang/OTP 24)
```

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir):
```
"dialyxir": {:hex, :dialyxir, "1.1.0", "c5aab0d6e71e5522e77beff7ba9e08f8e02bad90dfbeffae60eaf0cb47e29488", [:mix], [{:erlex, ">= 0.2.6", [hex: :erlex, repo: "hexpm", optional: false]}], "hexpm", "07ea8e49c45f15264ebe6d5b93799d4dd56a44036cf42d0ad9c960bc266c0b9a"},
```
### Current behavior
 * Describe current behavior. Include errors, stack traces, and any additional information that might be important here.
 Line numbers are no longer included in errors, this was a new error that showed up for us when upgrading to 1.12.1-otp-24.
`lib/genesis/account/external_crypto_transaction.ex:0:unmatched_return`

We intentionally created other unmatched_return errors and they all show up as line 0.

### Expected behavior
* A short description of the expected behavior.
The correct line number should be displayed with errors.

**Comment by jeremyjh** [comment]
This is an upstream issue, the next Erlang patch should fix it I think: https://github.com/erlang/otp/pull/4890
