### ISSUE TITLE
Error when trying to create PLT

### ISSUE THREAD

**Issue by sashaafm** [jeremyjh/dialyxir#44]
Hello, I'm getting this error on Ubuntu 15.10 with Elixir 1.2.3:

```
sashaafm@ubuntu:~/Documents/dialyxir$ mix dialyzer.plt
Starting PLT Core Build ... this will take awhile
dialyzer --output_plt /home/sashaafm/.dialyxir_core_18_1.2.3.plt --build_plt --apps erts kernel stdlib crypto public_key -r /usr/local/lib/elixir/bin/../lib/elixir/../eex/ebin /usr/local/lib/elixir/bin/../lib/elixir/../elixir/ebin /usr/local/lib/elixir/bin/../lib/elixir/../ex_unit/ebin /usr/local/lib/elixir/bin/../lib/elixir/../iex/ebin /usr/local/lib/elixir/bin/../lib/elixir/../logger/ebin /usr/local/lib/elixir/bin/../lib/elixir/../mix/ebin
** (ErlangError) erlang error: :enoent
    (elixir) lib/system.ex:450: System.cmd("dialyzer", ["--output_plt", "/home/sashaafm/.dialyxir_core_18_1.2.3.plt", "--build_plt", "--apps", "erts", "kernel", "stdlib", "crypto", "public_key", "-r", "/usr/local/lib/elixir/bin/../lib/elixir/../eex/ebin", "/usr/local/lib/elixir/bin/../lib/elixir/../elixir/ebin", "/usr/local/lib/elixir/bin/../lib/elixir/../ex_unit/ebin", "/usr/local/lib/elixir/bin/../lib/elixir/../iex/ebin", "/usr/local/lib/elixir/bin/../lib/elixir/../logger/ebin", "/usr/local/lib/elixir/bin/../lib/elixir/../mix/ebin"], [])
    lib/mix/tasks/dialyzer.plt.ex:72: Mix.Tasks.Dialyzer.Plt.build_plt/0
    lib/mix/tasks/dialyzer.plt.ex:56: Mix.Tasks.Dialyzer.Plt.run/1
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:363: Code.require_file/2
```

I tried to install it on another machine with the exact same Ubuntu set up and Elixir version and it worked. Erlang versions are also the same I think.

**Comment by techgaun** [comment]
@sashaafm it seems like your system does not have dialyzer. You would have to run `apt-get install erlang-dialyzer` and that should fix it.

**Comment by nnutter** [comment]
I made this same mistake, and its obvious in hindsight, but it might be useful to people that are new to Elixir to highlight, in the README's installation section, that this depends on `dialyzer`.

**Comment by jeremyjh** [comment]
@nnutter yes I have always built erlang from source with kerl so I didn't realize the ubuntu packages are split up so much more than the OTP distribution. I added a task for this to the next release; I'll check if the `:dialyzer` module and executable are available and quit with explanation if not as well as mentioning it in the readme.

**Comment by nnutter** [comment]
@jeremyjh Cool.  FYI, I'm on Fedora and the package is split out too.
