### ISSUE TITLE
mix dialyzer.plt doesn't update deps plt?

### ISSUE THREAD

**Issue by henryj** [jeremyjh/dialyxir#45]
If I do a `mix deps.update some-lib` and then run `mix dialyzer.plt` it shows me 
```
==> some-lib (compile)

Compiled src/api/some_api.erl

Nothing to do.
```
which is alright cause I did change some specs in some_api.erl

However, if I run `mix dialyzer` now, the spec change in some-lib doesn't take effect until I `rm -rf ~/.dialyxir_core_*` and run `mix dialyzer.plt` again.

I guess this should worth a bug report?

btw I use `dialyzer: [plt_add_deps: true],` in my mix.exs if that matters.

**Comment by jeremyjh** [comment]
Thanks for reporting this. mix dialyzer.plt will now invoke the --check-plt option of dialyzer, which is I'm pretty sure what everyone expects should happen.

**Comment by aaronjensen** [comment]
great, thanks
