### ISSUE TITLE
Format option for ignore file and output: {file, short_description}

### ISSUE THREAD

**Issue by Nezteb** [jeremyjh/dialyxir#492]
According to [the docs about Elixir term format](https://github.com/jeremyjh/dialyxir#elixir-term-format), the following options are supported for an ignore file:
```elixir
# .dialyzer_ignore.exs
[
  # {short_description}
  {":0:unknown_function Function :erl_types.t_is_opaque/1/1 does not exist."},
  # {short_description, warning_type}
  {":0:unknown_function Function :erl_types.t_to_string/1 does not exist.", :unknown_function},
  # {short_description, warning_type, line}
  {":0:unknown_function Function :erl_types.t_to_string/1 does not exist.", :unknown_function, 0},
  # {file, warning_type, line}
  {"lib/dialyxir/pretty_print.ex", :no_return, 100},
  # {file, warning_type}
  {"lib/dialyxir/warning_helpers.ex", :no_return},
  # {file}
  {"lib/dialyxir/warnings/app_call.ex"},
  # regex
  ~r/my_file\.ex.*my_function.*no local return/
]
```

`mix dialyzer --format ignore_file` returns a list of warnings using the `{file, warning_type}`, which is very useful.

I'd love to go one step further and generate a list of warnings with the format `{file, short_description}`. If a single file has more than one instance of a warning, a single line in the ignore file will end up ignoring all of the warnings. Sometimes I'd prefer to ignore each individual warning specifically.

For example, if `mix dialyzer --format short` gives me:
```
lib/something.ex:15:no_return Function init/1 has no local return.
lib/something.ex:26:no_return Function update/1 has no local return.
lib/something.ex:36:no_return Function refresh/1 has no local return.
lib/something.ex:45:no_return Function update_state_from_cache/2 has no local return.
lib/something.ex:49:no_return Function update_state_from_backend/2 has no local return.
```
Then this single ignore line will ignore all five of those warnings:
```elixir
# .dialyzer_ignore.exs
[
  # {file, warning_type}
  {"lib/something.ex", :no_return},
]
```

I'd like to be able to do:
```elixir
# .dialyzer_ignore.exs
[
  # {file, short_description}
  {"lib/something.ex", "Function init/1 has no local return."},
  {"lib/something.ex", "Function update/1 has no local return."},
  {"lib/something.ex", "Function refresh/1 has no local return."},
  {"lib/something.ex", "Function update_state_from_cache/2 has no local return."},
  {"lib/something.ex", "Function update_state_from_backend/2 has no local return."},
]
```
(The above example makes me realize: I don't know if "short description" always includes line number, which isn't ideal because as code is added/removed, the line number of that specific warning will change often. 🤔)

As for a format name, maybe something like `--format ignore_file_strict` or `--format ignore_file_verbose`?

**Comment by jeremyjh** [comment]
Yeah I think I like `ignore_file_strict`, and yes we'd need to leave off the line number and just include the warning text. 

I'd hate to break people but really it seems like this should be default, I agree its not really good to categorically ignore a warning type across a whole file.
