### ISSUE TITLE
0.4 Release Features

### ISSUE THREAD

**Issue by jeremyjh** [jeremyjh/dialyxir#50]
The 0.4 release (in progress in `develop` branch) is intended to address many deep and longstanding problems in dialyxir and will include significant changes to defaults which may well be "breaking" for some projects until configuration is removed or updated.

The general principal behind the changes is to provide:
        \*  simplest possible operation - less user configuration for expected usage
        \*  defaults appropriate for a new user of dialyzer
        \*  a smooth experience for projects built on popular frameworks such as Phoenix out-of-the-box
        \*  correct, complete results by default

See this [forum post](https://elixirforum.com/t/dialyxir-recent-updates-and-request-for-feedback) for more background.     

If you wish to contribute work on one of the unchecked items please create a new issue for it to claim it, referencing this issue. If you have other ideas you can make suggestions in this issue or open a new issue referencing this issue if you think it will need a lot of discussion.
# Dependencies
- [x] Include OTP applications from current mix 
- [x] Transitive OTP applications
  - [x] In umbrella projects 
    - [x] Even when invoked in the sub application
- [x] Transitive by default
- [x] Configure either OTP mode or project (mix) mode - default OTP
# PLT
- [x] `dialyze`  PLT file management, e.g. erlang/elixir core file copied into _build, app dependencies added only to this project local file
- [x] `dialyze`  plt update functionality (add/remove individual modules from dependencies) 
- [x] warn users of :plt_file about new file scheme (allow suppression of warning with :no_warn) e.g. plt_file: {:no_warn,"local.plt"}
- [x] use mix_home for core storage - config via :plt_core_path
- [x] warn users who have the old ~/.dialyxir*.plt files but no new core file about backward incompatibility in the 0.4.0 release
# Warnings
- [x] remove all default warnings
- [x] needs to be in the compatibility notice
# dialyzer task
- [x] check if dialyzer module is available
- [x] remove separate plt task
- [x] invoke plt task if plt file is not found
- [x] invoke plt task if dependencies have changed
  - use hash mix file and applications list to determine changes

**Comment by KronicDeth** [comment]
@jeremyjh when I `mix dialyzer` from individual app directories `apps/<name>` in an umbrella projecct, they end up adding their own modules and removing the previous app's modules because all the `apps/<name>` apps have the same `build_path` (`../../_build`).  This means that the caching isn't as efficient as it could be.  Should the apps have their own copy of the cache in the case where they have a shared build_path as is the default for `--umbrella`?

**Comment by jeremyjh** [comment]
This is in develop branch?

I think I have only tested running from the umbrella directory so far.

**Comment by KronicDeth** [comment]
Yes, it's in the develop branch.  I can run from the umbrella directory for now, but running from the individual apps is useful locally when only working on the one app and it allows to parallelize the build by doing `mix dialyzer`, `mix credo --strict` and `mix test` for each app separately.

**Comment by jeremyjh** [comment]
I think this can/should be supported, added it to the list. Will be a good reason to write the umbrella tests I was procrastinating!

**Comment by jeremyjh** [comment]
@KronicDeth I'm not sure this is going to be possible. The basic problem, is that when you start in a child project, that child project is loaded. If I try to run my recursion from the parent umbrella, it tries to load the child again. If I *don't* try to fully load my parent, just have it load the children other than the one it started with then child we're starting in can't find its own `.app` file when Application.load is called. 

This is unfortunate because I think it is a regression; the old dialyxir way of using a single .plt file and a separate task for plt means that you can just run the dialyzer.plt task once from the parent, then run mix dialyzer in the child and it probably works fine.

There is a workaround though, which is to run with --no-check from the child app. If you do change dependencies you will need to run `mix dialyzer` from the parent to update the plt. Another way to skin this, would be to simply apply --no-check when we detect being run from a child project, with a notice printed to the console.

Its still entirely possible that this can be made to work, and I pushed a branch `recurse-child` that has my attempt at it. Take a look if you'd like. I will either implement `no-check` workaround or fix this in the next week and release this.

**Comment by KronicDeth** [comment]
My work-around (using the older `mix dialyze`, which I know you've merged into `dialyxir`) was to define a new task that swaps the files back and forth

<details>
```elixir
defmodule Mix.Tasks.Dialyze.Umbrella.App do
  @moduledoc """
  Runs `mix dialyze` in an app using an app-specific PLT

  1. Swaps `_build/MIX_ENV/dialyze_erlang_ERLANG_VERSION_elixir-ELIXIR_VERSION-APP_deps-MIX_ENV` to
     `_build/MIX_ENV/dialyze_erlang_ERLANG_VERSION_elixir-ELIXIR_VERSION_deps-MIX_ENV`
  2. Runs `mix dialyze`
  3. Swaps `_build/MIX_ENV/dialyze_erlang_ERLANG_VERSION_elixir-ELIXIR_VERSION_deps-MIX_ENV` back to
     `_build/MIX_ENV/dialyze_erlang_ERLANG_VERSION_elixir-ELIXIR_VERSION-APP_deps-MIX_ENV`
  """

  alias Mix.Project

  use Mix.Task

  @preferred_cli_env :test
  @shortdoc "Run `mix dialyze` in an umbrella app using an independent PLT"

  # Functions

  ## Callbacks

  def run(args) do
    state = %{app_deps_plt_path: app_deps_plt(), deps_plt_path: deps_plt()}
    setup_app_deps_plt(state)
    swap_in_app_deps_plt(state)

    try do
      Mix.Task.run("dialyze", args)
    after
      swap_out_app_deps_plt(state)
    end
  end

  ## Private Functions

  defp app_deps_plt do
    app = Project.config()
          |> Keyword.fetch!(:app)

    name = "erlang-#{otp_vsn()}_elixir-#{System.version()}-#{app}_deps-#{build_env()}"
    local_plt(name)
  end

  defp build_env() do
    config = Project.config()
    case Keyword.fetch!(config, :build_per_environment) do
      true -> Atom.to_string(Mix.env())
      false -> "shared"
    end
  end

  defp deps_plt do
    name = "erlang-#{otp_vsn()}_elixir-#{System.version()}_deps-#{build_env()}"
    local_plt(name)
  end

  defp local_plt(name) do
    Path.join(Project.build_path(), "dialyze_" <> name <> ".plt")
  end

  defp otp_vsn() do
    major = :erlang.system_info(:otp_release)
    vsn_file = Path.join([:code.root_dir(), "releases", major, "OTP_VERSION"])
    try do
      {:ok, contents} = File.read(vsn_file)
      String.split(contents, "\n", trim: true)
    else
      [full] ->
        full
      _ ->
        major
    catch
      :error, _ ->
        major
    end
  end

  defp setup_app_deps_plt(%{app_deps_plt_path: app_deps_plt_path, deps_plt_path: deps_plt_path}) do
    unless File.exists?(app_deps_plt_path) do
      if File.exists?(deps_plt_path) do
        File.cp!(deps_plt_path, app_deps_plt_path)
      end
    end
  end

  defp swap_files(first, second) do
    tmp_first = "#{first}.tmp"
    File.rename(first, tmp_first)
    File.rename(second, first)
    File.rename(tmp_first, second)
  end

  defp swap_in_app_deps_plt(%{app_deps_plt_path: app_deps_plt_path, deps_plt_path: deps_plt_path}) do
    Mix.shell.info "Swapping app deps PLT into deps PLT used by `mix dialyze`"
    swap_maybe_files(app_deps_plt_path, deps_plt_path)
  end

  defp swap_out_app_deps_plt(%{app_deps_plt_path: app_deps_plt_path, deps_plt_path: deps_plt_path}) do
    Mix.shell.info "Swapping deps PLT used by `mix dialyze` to app deps PLT for caching"
    swap_maybe_files(deps_plt_path, app_deps_plt_path)
  end

  defp swap_maybe_files(maybe_first, maybe_second) do
    if File.exists?(maybe_first) do
      if File.exists?(maybe_second) do
        swap_files(maybe_first, maybe_second)
      else
        File.rename(maybe_first, maybe_second)
      end
    end
  end
end
```
</details>

**Comment by jeremyjh** [comment]
@KronicDeth So you actually want a different `plt` when you are running in the child project? I guess I was assuming you'd want to use the parent project's `plt` but analyze only the beams for the child project you are in.

**Comment by KronicDeth** [comment]
The goal for me was not to have different `plt` per child project, but it was the way I found to have each child project's `mix dialyze` not interfere (by adding unnecessary Adding Module or Removing Modules) with other child projects call of `mix dialyze`.
