### ISSUE TITLE
Use Dialyzer 

### ISSUE THREAD

**Issue by joeljuca** [jeremyjh/dialyxir#513]
Hi,

So, I have this macro that implements functions in other modules, and I would like to run Dialyzer against it. The problem is: IIUC, in order to run Dialyzer on these functions, I must `use MyMacroModule` in a target module so Dialyzer can recognize the functions, etc.

It works, just as expected. But, This is a module intended to be used by other projects – so there's no target module in the `lib/` directory. I do have some target modules that `use MyMacroModule` under `test/support/`, but they are not being "seen" by Dialyzer when I run `mix dialyzer`. I actually managed to solve it by including `test/support` to `elixirc_paths` when `MIX_ENV` was either `dev` or `test` - but then, I got my test modules included in doc generation (`mix docs`). 🥲

I've messed things up, but I do not understand how to include `test/support/*` files in Dialyzer modules paths without using `elixirc_paths`.

Help?

### Precheck

- [x] Take a look at the open issues and be sure that your issue is not already covered.
- [x] Be sure your versions of Dialyxir and Erlex are up to date.

### Environment

* Elixir & Erlang/OTP versions (elixir --version):

```
$ elixir --version
Erlang/OTP 25 [erts-13.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit]

Elixir 1.14.4 (compiled with Erlang/OTP 25)
```

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir):

```
$ cat mix.lock | grep dialyxir
  "dialyxir": {:hex, :dialyxir, "1.3.0", "fd1672f0922b7648ff9ce7b1b26fcf0ef56dda964a459892ad15f6b4410b5284", [:mix], [{:erlex, ">= 0.2.6", [hex: :erlex, repo: "hexpm", optional: false]}], "hexpm", "00b2a4bcd6aa8db9dcb0b38c1225b7277dca9bc370b6438715667071a304696f"},
```

**Comment by joeljuca** [comment]
The module is actually published on Hex, so if you want to see it for yourself, here's the important parts:

- [the module containing the macro](https://github.com/joeljuca/swiss_schema/blob/v0.3.2/lib/swiss_schema.ex#L6)
- [the elixirc_paths tweak in mix.exs](https://github.com/joeljuca/swiss_schema/blob/v0.3.2/mix.exs#L24-L25)
- [the test modules that `use` the macro](https://github.com/joeljuca/swiss_schema/blob/v0.3.2/test/support/schema.ex#L3)

**Comment by joeljuca** [comment]
And here's my test module being included in the documentation. 🤦‍♂️

https://hexdocs.pm/swiss_schema/0.3.2/SwissSchemaTest.User.html

**Comment by jeremyjh** [comment]
Dialyxir will analyze compiled modules if you tell it where to look - your question is more about how to compile elixir modules without including them in documentation. Did you try `@moduledoc false` ? https://hexdocs.pm/elixir/1.12.3/writing-documentation.html#hiding-internal-modules-and-functions

**Comment by joeljuca** [comment]
@jeremyjh setting `@moduledoc` to `false` solves my immediate problem for now. Thanks for pointing me in the right direction!
