### ISSUE TITLE
Exit Status

### ISSUE THREAD

**Issue by novaugust** [jeremyjh/dialyxir#52]
I was hoping to get dialyzer worked into my CI, but noticed that `mix dialyzer`always exits with 0, which means it's eating up the actual exit status.

>      0 - No problems were encountered during the analysis and no
          warnings were emitted.
     1 - Problems were encountered during the analysis.
     2 - No problems were encountered, but warnings were emitted.

**Comment by jeremyjh** [comment]
You can pass a command line argument, --halt-exit-status and it will terminate with the dialyzer status. This isn't the default because we want to play nice with `mix do`.

**Comment by novaugust** [comment]
Ah sorry, I thought I had hit cancel rather than file this as I did manage to find that in the middle of writing this up. It works fine for ci as long as it's run subsequent to mix test,  thanks
