### ISSUE TITLE
Dialyxir fails on phoenix_storybook with tons of unknown_function errors

### ISSUE THREAD

**Issue by cblavier** [jeremyjh/dialyxir#520]
Hey there 👋 

I'm the maintainer of the author of the [phoenix_storybook](https://github.com/phenixdigital/phoenix_storybook) library, and I used to have dialyxir running well on the project in CI.
I had to disable it a few months ago because it stopped working and I just started investigating why.

Here is the [branch](https://github.com/phenixdigital/phoenix_storybook/tree/317-dialyzer-is-no-longer-working) I'm using for this specific issue.

When running `mix dialyzer` (erlang 26.0.2 / elixir 1.15.6-otp-26) I have the following [output](https://gist.github.com/cblavier/a906b6d44dc919d021db137d1d39c6f6)

Any help would be much appreciated 😄 
Thanks 🙏

(matching issue on storybook project 👉 [#317](https://github.com/phenixdigital/phoenix_storybook/issues/317))

**Comment by deadshot465** [comment]
We're in a similar situation here where dialyxir used to run perfectly fine in CI but now no longer works due to a whole bunch of unknown_function errors.

**Comment by cblavier** [comment]
You're my hero! It indeed fixed it
Thanks!

**Comment by etehtsea** [comment]
@cblavier you are welcome :)

Also, adding `hex` to the ignore list seems to resolve the issue:

```
dialyzer: [
  plt_ignore_apps: [:hex]
]
```
