### ISSUE TITLE
error while running dialyxir

### ISSUE THREAD

**Issue by epinault** [jeremyjh/dialyxir#523]
### Precheck

Per #467 , opening a new issue., Will see if I can get a repro from private code

### Environment

* Elixir & Erlang/OTP versions (elixir --version): elixir 1.15, OTP 26

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir): 1.4.2

### Current behavior

Please file a bug in https://github.com/jeremyjh/dialyxir/issues with this message.
Unknown error occurred: %FunctionClauseError{module: Dialyxir.Warnings.InvalidContract, function: :format_long, arity: 1, kind: nil, args: nil, clauses: nil}
Legacy warning:
lib/halberd_client/http_client.ex:10: Invalid type specification for function 'Elixir.HalberdClient.HTTPClient':get/2.
 The success typing is 'Elixir.HalberdClient.HTTPClient':get(binary(),'nil' | maybe_improper_list() | map()) -> {'error',_} | {'ok',#{'__client__':=#{'__struct__':='Elixir.Tesla.Client', 'adapter':='nil' | {_,_} | {_,_,_}, 'fun':=_, 'post':=[any()], 'pre':=[any()]}, '__module__':=atom(), '__struct__':='Elixir.Tesla.Env', 'body':=_, 'headers':=[{_,_}], 'method':='delete' | 'get' | 'head' | 'options' | 'patch' | 'post' | 'put' | 'trace', 'opts':=[{_,_}], 'query':=[{_,_}], 'status':='nil' | integer(), 'url':=binary()}}
 But the spec is 'Elixir.HalberdClient.HTTPClient':get('Elixir.Tesla.Env':url(),'Elixir.Tesla':option()) -> 'Elixir.Tesla.Env':result()
 They do not overlap in the 2nd argument

### Expected behavior
* A short description of the expected behavior.

**Comment by epinault** [comment]
thanks for fixing this? when do you think we can get this released?

**Comment by jeremyjh** [comment]
Hi, just released 1.4.4 on Hex.
