### ISSUE TITLE
Not reporting an issue on type spec

### ISSUE THREAD

**Issue by sygour** [jeremyjh/dialyxir#529]
First things first, thanks for the excellent work, I find using dialyzer quite easy and helpful 👍 

### Precheck

* Take a look at the open issues and be sure that your issue is not already covered.
* Be sure your versions of Dialyxir and Erlex are up to date.

### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```
Erlang/OTP 26 [erts-14.2.1] [source] [64-bit] [smp:10:10] [ds:10:10:10] [async-threads:1] [jit] [dtrace]
Elixir 1.15.6 (compiled with Erlang/OTP 26)
```

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir):
```
  "dialyxir": {:hex, :dialyxir, "1.4.3", "edd0124f358f0b9e95bfe53a9fcf806d615d8f838e2202a9f430d59566b6b53b", [:mix], [{:erlex, ">= 0.2.6", [hex: :erlex, repo: "hexpm", optional: false]}], "hexpm", "bf2cfb75cd5c5006bec30141b131663299c661a864ec7fbbc72dfa557487a986"}
```

### Current behavior
 * Describe current behavior. Include errors, stack traces, and any additional information that might be important here.

Here is a sample code to reproduce:
```elixir
defmodule SilentDialyzer do
  @spec public_function() :: :ok
  def public_function() do
    IO.inspect(private_function(0))
    IO.inspect(private_function(1))
    IO.inspect(private_function(2))
    IO.inspect(private_function(3))
    IO.inspect(private_function(4))
    :ok
  end

  @spec private_function(integer()) :: {:ok, String.t()}
  defp private_function(int) do
    case int do
      0 -> {:ok, "0"}
      1 -> {:ok, int}
      2 -> {:error, "2"}
      3 -> {:error, int}
      4 -> :ignored
    end
  end
end
```

Running `mix dialyzer` is successful.

### Expected behavior
* A short description of the expected behavior.

`mix dialyzer` should exit with an error.
As you can see in the sample, `private_function` contract is not correct, it should be something like
```elixir
@spec private_function(integer()) :: {:ok, any()} | {:error, any()} | :ignored
```

**Comment by jeremyjh** [comment]
This is really a question about Erlang's dialyzer, which is out of scope for this project which just handles integration with Elixir. If I knew the answer I'd tell you, but the best place to ask this kind of thing is on elixirforums.com.
