### ISSUE TITLE
Unknown error occurred

### ISSUE THREAD

**Issue by RaymondLoranger** [jeremyjh/dialyxir#533]
Erlang/OTP 26 [erts-14.2.2] [source] [64-bit] [smp:8:8] [ds:8:8:10] [async-threads:1] [jit:ns]
Elixir 1.16.1 (compiled with Erlang/OTP 26)
Dialyxir 1.4.3

Please file a bug in https://github.com/jeremyjh/dialyxir/issues with this message.

Unknown error occurred: %FunctionClauseError{module: Dialyxir.Warnings.InvalidContract, function: :format_long, arity: 1, kind: nil, args: nil, clauses: nil}

Legacy warning:
lib/hangman/engine.ex:78: Invalid type specification for function 'Elixir.Hangman.Engine':make_move/2.
 The success typing is 'Elixir.Hangman.Engine':make_move(binary(),binary()) -> any()
 But the spec is 'Elixir.Hangman.Engine':make_move('Elixir.Hangman.Game':name(),'Elixir.Hangman.Game':letter()) -> 'Elixir.Hangman.Game':tally()
 They do not overlap in the 2nd argument
________________________________________________________________________________
done (warnings were emitted)
Halting VM with exit status 2

**Comment by RaymondLoranger** [comment]
Initially, module `Hangman.Game` had `letter` defined as `String.codepoint()` and I had no error messages. But then I changed the type to `byte` and it caused this error message.

**Comment by jeremyjh** [comment]
@RaymondLoranger is there a repo I can use to reproduce the issue?

**Comment by RaymondLoranger** [comment]
Hi Jeremy,

 

Yes, there is a repo (it is a hex package): https://hex.pm/packages/hangman_game

To reproduce the issue you would need to replace lib/hangman/game.ex:22 from

@type letter :: <<_::8>>

to 

@type letter :: byte

 

Regards,

Raymond
