### ISSUE TITLE
Change PLTs filename/target folder

### ISSUE THREAD

**Issue by NobbZ** [jeremyjh/dialyxir#54]
For CI-caching I do need to save the core PLT file at a different location than `$HOME`. It seems that `plt_core_path: ".cache/"` is ignored, and still the PLT files from whereever are taken into account, I can't even find something in `$HOME`, but `mix dialyzer` complains if it is not set...

**Comment by NobbZ** [comment]
OK, after changing that setting, I had to remove `_build` and `deps` and then re-`mix deps.get` to make it happen.

Can't we check this on every run?

**Comment by jeremyjh** [comment]
If it already built a project specific PLT it would not have cause to touch core files. It only uses the core files to copy to the project _build folder when there is nothing there to start with, they are not used for analysis.

**Comment by jeremyjh** [comment]
If what you really wanted to change is the location of your project-specific PLT file then you want to use the :plt_file option. If you changed both that and the :plt_core_path it would build everything on next run.

**Comment by NobbZ** [comment]
`:plt_file` wasn't documented anymore in the README, so I thought it has been replaced by the `:plt_core_path` option.

**Comment by NobbZ** [comment]
Now since I am using `:plt_file`, I do get the following warning:

> Notice: :plt_path is deprecated as Dialyxir now uses project-private PLT files by default.
If you want to use this setting without seeing this warning, provide it in a pair
with the :no_warn key e.g. \`dialyzer: plt_file: {:no_warn, "~/mypltfile"}\`

This reads a bit confusing, since it mentions something as depracted which I didn't use, and tells you to fix it by pointing you to something you did use.

**Comment by NobbZ** [comment]
By only building the core files into the cache and keeping `:plt_file` unset, I still have built times around 5 to 10 minutes in CI, because the dev PLT is rebuilt everytime which does contain about 60 moudles more than the core PLT.

And I do currently only have `credo` and `dialyxir` as dev-only dependencies and no other dependencies.

The project itself is currently empty, I am just trying to set up CI and get it dialyzer into acceptable build-times.

So to get acceptable built-times I have to use a deprecated option, which I'd prefer not to do. I think this will be an issue in other workflows as well.

There are valid reasons to beeing able to control the location of the various PLT-files, so can you please un-deprecate `:plt_file`? Maybe still couple it with a warning and the `:no_warn`-tuple, but also with the promise to not remove it in the future?

**Comment by jeremyjh** [comment]
Yes, I can change the messaging on it. I want to discourage people using it
for the wrong reason but I do not plan to remove it.

Curious about build times - sounds like nothing extra should go into your
project PLT.
Or maybe you have something like :logger in your applications list?

Or you are using plt_add_deps transitive, project or true which will add
Dev deps. If you are using one of those can you try removing it?

**Comment by NobbZ** [comment]
I do not have `:plt_add_deps` set, so it should be at its default.

And yes, `:logger` IS in the list of applications, as it is in every fresh created elixir-application. And even after removing it, I get long buildtimes. https://gitlab.com/NobbZ/irc_ex/builds/5883228 is running for ~8 minutes now and still not finished.
