### ISSUE TITLE
No .beam files to analyze (no --src specified?)

### ISSUE THREAD

**Issue by dan-cooke** [jeremyjh/dialyxir#548]
### Environment

* Elixir & Erlang/OTP versions (elixir --version):
```

Erlang/OTP 27 [erts-15.1] [source] [64-bit] [smp:32:32] [ds:32:32:10] [async-threads:1] [jit:ns]

Elixir 1.17.3 (compiled with Erlang/OTP 27)

```

* Which version of Dialyxir are you using? (cat mix.lock | grep dialyxir):
```
  "dialyxir": {:hex, :dialyxir, "1.4.4", "fb3ce8741edeaea59c9ae84d5cec75da00fa89fe401c72d6e047d11a61f65f70", [:mix], [{:erlex, ">= 0.2.7", [hex: :erlex, repo: "hexpm", optional: false]}], "hexpm", "cd6111e8017ccd563e65621a4d9a4a1c5cd333df30cebc7face8029cacb4eff6"},

```

### Current behavior
1. Bootstrap a new mix project `mix new broken`
2. `cd broken`
3. Follow guide for setting up dialyxir
4. `mix dialyzer`

```
Finding suitable PLTs
Checking PLT...
[:compiler, :elixir, :kernel, :learning, :logger, :stdlib]
PLT is up to date!
No :ignore_warnings opt specified in mix.exs and default does not exist.

Starting Dialyzer
[
  check_plt: false,
  init_plt: ~c"/home/dan/dev/elixir/learning/_build/dev/dialyxir_erlang-27.1_elixir-1.17.3_deps-dev.plt",
  files: [],
  warnings: [:unknown]
]
:dialyzer.run error: Analysis failed with error:
No .beam files to analyze (no --src specified?)
Consider setting some default apps in your dialyzer.config file

Halting VM with exit status 1

```
### Expected behavior
Static analysis

Apologies if i'm doing something dumb, i've searched lots of places on the web and I cannot find anyone else getting this error message.

i've tried reinstalling elixir, switching to dev build - nothing seems to work

**Comment by jeremyjh** [comment]
@dan-cooke I've never seen it either. After you run `mix compile` are there BEAM files for your modules in the _build folder? If you could publish a test project that reproduces I'd like to try it.

**Comment by dan-cooke** [comment]
@jeremyjh thanks! I’ll get a reproduction repo when I get a chance

There are BEAM files in the build directory which is even more confusing

**Comment by dan-cooke** [comment]
@jeremyjh any project I init will reproduce this issue, its got to be something up with my system. As mentioned in the OP, you can just do `mix new broken` and install dialyxir and this issue will occur

Really wish I could resolve this as its holding me back from really picking up Elixir
