### ISSUE TITLE
Can't run `mix dialyzer.plt` when a mix dependency

### ISSUE THREAD

**Issue by jclem** [jeremyjh/dialyxir#60]
Adding Dialyxir as a mix dependency only adds the `mix dialyzer` task, but not `mix dialyzer.plt`. In the meantime, I've manually added `mix dialyzer.plt` to one of my projects by yanking some code from [`Mix.Tasks.Dialyzer`](https://github.com/jeremyjh/dialyxir/blob/master/lib/mix/tasks/dialyzer.ex). 

This is useful in environments like CircleCI where I want `mix dialyzer` run in my test phase, but `mix dialyzer.plt` run in my dependencies phase where its output can be cached.

This would be preferable to having to install dialyzer globally so that I can run the commands separately.

**Comment by jeremyjh** [comment]
I'll probably add it back as a command line switch rather than a separate task. That should work right?

**Comment by jclem** [comment]
Yeah that'd be fine!

**Comment by jclem** [comment]
Yeah that'd be fine!

**Comment by jeremyjh** [comment]
As of 0.4.3 on hex you can use `mix dialyzer --plt` to just build the PLT and exit.
