### ISSUE TITLE
Full path to files in warnings

### ISSUE THREAD

**Issue by Zert** [jeremyjh/dialyxir#62]
I have the project structure like this:
```
lib
    abcd
        protocol.ex
    efgh
        protocol.ex
    ijkl
        protocol.ex
```

Elixir allow this, it is awesome!

When I run `mix dialyzer` I see a warning:

```
...
protocol.ex:230: The pattern {'error', _error@1} can never match the type 'ok'
...
```

but I cannot say certain, which of `protocol.ex` files affected.

Could you please add the full path to files? May be from the current directory.

**Comment by jeremyjh** [comment]
Currently this isn't possible because `dialyxir` just shells the Erlang `dialyzer` program and I do not have control of its output. In a future release I do plan to switch to using the API and then would be able to support this.
