### ISSUE TITLE
Pretty output

### ISSUE THREAD

**Issue by daveshah** [jeremyjh/dialyxir#67]
I was wondering what your thoughts were on 'prettying' up the output from dialyzer so that the warnings would stand out a bit more. I hacked together a crude approach [here](https://github.com/daveshah/dialyxir/commit/421454c66d9dabeccd03d211fd46e1c2eac39090). Thoughts? :)

**Comment by jeremyjh** [comment]
Definitely we should have it. My plan is to address it after we move to using `dialyzer:run` API so that we're dealing with output in a data structure rather than strings - which will make it a little cleaner code. I don't mind pulling in something like what you have there for now though.

**Comment by daveshah** [comment]
Good call on that. The string route seems sketchy as a long term solution. In the interim, I'll cleanup my fork and make a PR :) Thanks! 👍

**Comment by daveshah** [comment]
On a (somewhat) related topic: regarding your above comment 

> My plan is to address it after we move to using dialyzer:run API

Has the work on that already started? If not, are you open to opening up an issue and corresponding PR for it? I was taking a look last night and thought it might be fun to start thinking through that (unless it's something you're already in the middle of tackling)

**Comment by jeremyjh** [comment]
@daveshah I have some thoughts on it but haven't started and you would be welcome to Work on it. I'll open an issue tonight to lay out my current thoughts/requirements.

**Comment by daveshah** [comment]
Excellent! Thanks @jeremyjh! Looking forward to it 👍

**Comment by jeremyjh** [comment]
@daveshah created #69
