### ISSUE TITLE
Using the :dialyzer.run API

### ISSUE THREAD

**Issue by jeremyjh** [jeremyjh/dialyxir#69]
Presently `dialyxir` shells out to the `dialyzer` command line program to perform analysis. This is undesirable because it imposes the cost of launching a whole VM just to perform analysis. This was not a conscious decision but simply a reflection of the fact that `dialyxir` began its life as the barest evolution of a shell script I'd been using. 

The [Erlang API](http://erlang.org/doc/man/dialyzer.html#gui-1) documentation is fairly straightforward. We have to build up a data structure containing all the required options and pass them to the `:dialyzer.run` function. 

There is a [working example](https://github.com/fishcakez/dialyze/blob/master/lib/mix/tasks/dialyze.ex#L435) in the dialyze project, the most relevant code:

```elixir
...
     plt_run([analysis_type: :succ_typings, plts: [plt], files: files,
          warnings: warnings])
   
  defp plt_run(opts) do
    :dialyzer.run([check_plt: false] ++ opts)
  end
```

## Warnings

You can see how they are structured at the bottom of the Erlang doc, you'll having a list of {:warning_name, {'filename', linenumber}, msg}.   `dialyzer` just prints them; of course we want to keep them colorized but it will be easier to have different color/styling for the the filename, line number, warning summary and the message itself.  

We can also group by module/file in some way visually, so that warnings from a single file visually fit together and down the line there might be something useful we could do knowing the categories of errors that user just saw; such as making it easier for them to find help info.

## Compatibility

1. By default the CLI returns warnings about unknown functions - keeping this the default means passing `:unknown` as one of the options.  
2. Presently users can pass flags to dialyzer either by including them a `flags: ["-Wno..."]` in their mix.exs or passing them on the command line. Any command line parameter that `dialyxir` isn't looking for just gets passed along to `dialyzer`. 

Number 2 is a little tricky but I think we have to map the flags to the atom names to do what the user means. e.g. we have to map "-Wno_unused" to `:no_unused` . We also want to let the user pass us atoms, e.g. they could have `dialyzer: flags: [:no_unused, :unmatched_returns]` in their Mix project.

If we have to break strict compatibility we can - we'd make this the primary feature of the `0.5` release. But we should do what we can to keep likely configurations working after the update.

**Comment by daveshah** [comment]
Thanks for getting this out there. I think your explanation of 2 above makes it seem less tricky so thats promising :) If you're cool w/it - I'll branch and start the ball rolling on this 👍

**Comment by jeremyjh** [comment]
Absolutely, be my guest.
