### ISSUE TITLE
[Bug?] The exit code for `mix dialyzer` not the same as calling dialyzer directly?

### ISSUE THREAD

**Issue by amorphid** [jeremyjh/dialyxir#74]
Is this a bug, or intentional?

Running `mix dialyzer`, the exit code is `0`

    $ mix dialyzer

    dialyzer --no_check_plt --fullpath --plt /Users/amorphid/my/code/github.com/amorphid/docker_hub/_build/dev/dialyxir_erlang-19.2_elixir-1.4.1_deps-dev.plt /Users/amorphid/my/code/github.com/amorphid/docker_hub/_build/dev/lib/docker_hub/ebin

    Proceeding with analysis...
    lib/docker_hub.ex:6: Invalid type specification for function 'Elixir.DockerHub':hello/0. The success typing is () -> 'world'
     done in 0m2.88s
    done (warnings were emitted)

    $ echo $?
    
    0

Running `dialyzer` directly, the exit code is `2`

    $ dialyzer --no_check_plt --fullpath --plt

    /Users/amorphid/my/code/github.com/amorphid/docker_hub/_build/dev/dialyxir_erlang-19.2_elixir-1.4.1_deps-dev.plt /Users/amorphid/my/code/github.com/amorphid/docker_hub/_build/dev/lib/docker_hub/ebin

    Proceeding with analysis...
    lib/docker_hub.ex:6: Invalid type specification for function 'Elixir.DockerHub':hello/0. The success typing is () -> 'world'
     done in 0m2.88s
    done (warnings were emitted)

    $ echo $?
    
    2

**Comment by jeremyjh** [comment]
It is intentional; mix does not provide a way to set the exit status from a task. The only way to do it is to halt the VM which would break mix do chains. If you want to do this, pass --halt-exit-status argument.

```shell
$ mix dialyzer --halt-exit-status
```

**Comment by amorphid** [comment]
Gotcha, thanks.
