### ISSUE TITLE
ignore_warnings does not set exit status 0 if all warnings filtered out

### ISSUE THREAD

**Issue by arnodirlam** [jeremyjh/dialyxir#76]
Setting
```
dialyzer: [plt_add_deps: :transitive, plt_add_apps: [:inets], ignore_warnings: ".dialyzerignore"]
```
in a phoenix project with the `.dialyzerignore` file in place, calling
```
mix dialyzer --halt-exit-status
```
shows no warnings but returns an exit status > 0.

Using dialyxir 0.4.4

**Comment by daveshah** [comment]
I believe this should be corrected in #73.

**Comment by arnodirlam** [comment]
Unfortunately not. Used your branch as dependency, and now the `ignore_warnings` seems to be ignored completely:

```
Starting Dialyzer
dialyzer args: [check_plt: false,
 init_plt: '/Users/arno/dev/vira-elixir/_build/dev/dialyxir_erlang-19.2_elixir-1.4.2_deps-dev.plt',
 files_rec: ['/Users/arno/dev/vira-elixir/_build/dev/lib/vira/ebin'],
 warnings: [:unknown]]
done in 0m5.02s
auth.ex:30: Function create_jwt/1 has no local return
auth.ex:30: Function create_jwt/2 has no local return
auth.ex:38: The call 'Elixir.Joken':with_exp(#{'__struct__':='Elixir.Joken.Token', 'claims':=#{'iss':=_, _=>_}, _=>_},pos_integer()) breaks the contract ('Elixir.Joken.Token':t(),non_neg_integer()) -> 'Elixir.Joken.Token':t()
done (warnings were emitted)
```

What did work with your branch (only) was changing the line in `.dialyzerignore` from `lib/vira/auth.ex` to just `auth.ex`. No warnings and exit code 0, as expected. However, I'd expect it to behave like `.gitignore` syntax where the path relative to the repo works.

**Comment by jeremyjh** [comment]
Can you check if the ignore warnings in your file actually still match the
output? Output formatting has changed a bit in that branch.

**Comment by arnodirlam** [comment]
Yea that's right. It seems to be connected to the changed output format: The file path is not shown any more, only the file name. Adding the latter to the ignore file mutes the corrsponding warnings and sets exit code 0 (if no other warnings occurred).

What if I have multiple files with the same name in different paths? Can I only ignore all of them or none now?

**Comment by jeremyjh** [comment]
I think we missed that - we were passing --fullpath in the command line version. @daveshah do you mind submitting a PR to include path with the file name?

**Comment by daveshah** [comment]
Will do. Thx @arnodirlam & @jeremyjh

**Comment by daveshah** [comment]
PR posted. Let me know if that helps 👍

**Comment by jeremyjh** [comment]
It's merged, thanks @daveshah!

**Comment by arnodirlam** [comment]
Yep, works as expected. Thanks! 👍

**Comment by jdangerx** [comment]
Hm - when I try to run this I get 
```
:dialyzer.run error: Unknown dialyzer warning option: fullpath
```

Looking at the [dialyzer docs](http://erlang.org/doc/man/dialyzer.html#format_warning-1) I only see reference to `format_warning/1`, so I'm confused about all this `format_warning/2` stuff you're talking about.

**Comment by daveshah** [comment]
@jdangerx - out of curiosity, what version of Elixir & erlang are you using?
While the doc link you provided above doesn't call it out, (as it isn't present [in older versions](https://github.com/erlang/otp/blob/maint-r13/lib/dialyzer/src/dialyzer.erl#L41) ) it is available in [newer versions](https://github.com/erlang/otp/blob/maint-r14/lib/dialyzer/src/dialyzer.erl#L42)

**Comment by jeremyjh** [comment]
I think it's an error in the docstring, which referenced format_warning/1
twice. But that does not explain the error he is getting - can you please
paste the entire output @jdangerx ?


%% - format_warning/1: Get the string representation of a warning.
%% - format_warning/1: Likewise, but with an option whether
%% to display full path names or not
%% - plt_info/1: Get information of the specified plt.

**Comment by jeremyjh** [comment]
Also any chance you are passing --fullpath on the command line yourself?

**Comment by jdangerx** [comment]
I'm on Elixir 1.3.4 and Erlang 19; I was getting

```
Checking PLT...
[:absinthe, :absinthe_plug, :asn1, :base64url, :bugsnag, :cachex, :certifi,
 :combine, :compiler, :connection, :cowboy, :cowlib, :crypto, :db_connection,
 :decimal, :deppie, :ecto, :eex, :elixir, :elixometer, :eternal, :exometer,
 :exometer_core, :gettext, :goldrush, :guardian, :hackney, :httpoison, :idna,
 :jose, :kernel, :lager, :logger, :mariaex, :memcachex, :metrics, :mime,
 :mimerl, :mix, :phoenix, :phoenix_ecto, :phoenix_pubsub, :plug, :plugsnag,
 :pobox, :poison, :poolboy, :public_key, :ranch, :setup, ...]
Finding suitable PLTs
Looking up modules in dialyxir_erlang-19.2_elixir-1.3.4_deps-dev.plt
Finding applications for dialyxir_erlang-19.2_elixir-1.3.4_deps-dev.plt
Finding modules for dialyxir_erlang-19.2_elixir-1.3.4_deps-dev.plt
Checking 1689 modules in dialyxir_erlang-19.2_elixir-1.3.4_deps-dev.plt
Starting Dialyzer
[check_plt: false,
 init_plt: '/home/john/api/_build/dev/dialyxir_erlang-19.2_elixir-1.3.4_deps-dev.plt',
 files_rec: ['/home/john/api/_build/dev/lib/tpt_api/ebin'],
 warnings: [:fullpath, :unknown]]
:dialyzer.run error: Unknown dialyzer warning option: fullpath
```
And I *was* passing `flags: ["--fullpath"]` in my `mix.exs`. Commenting that out fixed the issue :)
