### ISSUE TITLE
ignore_warnings if empty crash dialyzer

### ISSUE THREAD

**Issue by losco** [jeremyjh/dialyxir#77]
If you set in mix.exs `dialyzer: [ignore_warnings: "dialyzer.ignore-warnings"]` and use and empty dialyzer.ignore-warnings, it will crash on `mix dialyzer`.

**Comment by jeremyjh** [comment]
Have you tried this on 0.4.4? This was previously reported in #72 and fixed.

**Comment by daveshah** [comment]
@jeremyjh looks like this is happening on master as well. #73 seems to help with this regression though.

**Comment by jeremyjh** [comment]
I found it. I didn't handle the case that no warnings are emitted. I think
we could let #73 fix it but I was planning to bump to 0.5 for that so a lot
of people won't pick that up right away. I don't really feel like I need to
make a maintenance branch though, I will focus on reviewing and merging #73
for now.

**Comment by daveshah** [comment]
Cool. I'll see if I can add a test for this too so we don't have another regression in the future 👍
