### ISSUE TITLE
ArgumentError on mix dialyze

### ISSUE THREAD

**Issue by avdgaag** [jeremyjh/dialyxir#80]
I’m running into this issue when trying to run `mix dialyze` on my CI service (CircleCI in this case) while everything seems fine locally. It points to [this line](https://github.com/jeremyjh/dialyxir/blob/dec52946710f1994777bbff4f3b403abb3141d84/lib/dialyxir/project.ex#L64) but I can’t tell what’s wrong, since `:erlang.system_info(:otp_release)` ([here](https://github.com/jeremyjh/dialyxir/blob/dec52946710f1994777bbff4f3b403abb3141d84/lib/dialyxir/project.ex#L67)) returns the same `'19'` for me, locally.

```
Checking PLT...
[:compiler, :connection, :cowboy, :cowlib, :crypto, :db_connection, :decimal,
 :ecto, :eex, :elixir, :gettext, :kernel, :logger, :mime, :phoenix,
 :phoenix_ecto, :phoenix_html, :phoenix_pubsub, :plug, :poison, :poolboy,
 :postgrex, :ranch, :stdlib]
** (ArgumentError) argument error
    :erlang.byte_size('19')
    lib/dialyxir/project.ex:64: Dialyxir.Project.erlang_plt/0
    lib/dialyxir/project.ex:7: Dialyxir.Project.plts_list/2
    lib/mix/tasks/dialyzer.ex:128: Mix.Tasks.Dialyzer.check_plt/0
    lib/mix/tasks/dialyzer.ex:110: Mix.Tasks.Dialyzer.run/1
    (mix) lib/mix/task.ex:294: Mix.Task.run_task/3
    (mix) lib/mix/task.ex:326: Mix.Task.run_alias/3
    (mix) lib/mix/task.ex:259: Mix.Task.run/2
    (mix) lib/mix/cli.ex:58: Mix.CLI.run_task/2
    (elixir) lib/code.ex:370: Code.require_file/2
```

Any clue as to what’s going on?

**Comment by jeremyjh** [comment]
Can you check the output of 

Path.join([:code.root_dir(), "releases", '19', "OTP_VERSION"])

Does that point to a file that is readable?

**Comment by avdgaag** [comment]
It returns `/home/ubuntu/dependencies/otp_src_19.2/releases/19/OTP_VERSION` which is not a readable file. There _is_ a file `/home/ubuntu/dependencies/otp_src_19.2/OTP_VERSION`.

My CI server builds Erlang from source:

```
export ERLANG_VERSION="19.2"
curl -L -O http://www.erlang.org/download/otp_src_$ERLANG_VERSION.tar.gz
tar xzf otp_src_$ERLANG_VERSION.tar.gz
cd $ERLANG_PATH
./configure --enable-smp-support \
            --enable-m64-build \
            --disable-native-libs \
            --disable-sctp \
            --enable-threads \
            --enable-kernel-poll \
            --disable-hipe \
            --without-javac
make
```

Would that be why the `OTP_VERSION` file is in an unexpected location?

**Comment by jeremyjh** [comment]
Possibly but this should work anyway - I think this code is making an
unsafe assumption and needs to be revisited.

**Comment by daveshah** [comment]
I haven't installed Erlang in the manner mentioned above nor set up CI in this way, but that said, this seems to fall in line with [this](http://erlang.org/doc/system_principles/versions.html):

> In an OTP source code tree, the OTP version can be read from the text file <OTP source root>/OTP_VERSION. The absolute path to the file can be constructed by calling **filename:join([code:root_dir(), "OTP_VERSION"]).**

> In an installed OTP development system, the OTP version can be read from the text file <OTP installation root>/releases/<OTP release number>/OTP_VERSION. The absolute path to the file can by constructed by calling **filename:join([code:root_dir(), "releases", erlang:system_info(otp_release), "OTP_VERSION"]).**

That said, should we make the `otp_vsn/1` function a little more robust in being able to handle both cases @jeremyjh ?

**Comment by jeremyjh** [comment]
How would we figure out the path of the source tree? Wouldn't that just wherever they happened to unpack it?

@avdgaag are you actually running `make install` ?

**Comment by daveshah** [comment]
I think it would be wherever they unpack it so perhaps it would have to be another configuration option.

**Comment by jeremyjh** [comment]
I tried building with those same options in a virgin ubuntu docker image and it works fine. It looks like you are running erlang out of the source tree rather than running `make install` which will install it properly. If this isn't the case or you aren't able to do that in your CI for some reason we can re-open this and discuss a config option but I presently don't think it is needed.

**Comment by avdgaag** [comment]
My setup script indeed does _not_ run `make install`. There’s a good chance that if it would, this would all work fine. I’ll try to make that work and re-open this issue if it doesn’t. Thanks for investigating!

**Comment by avdgaag** [comment]
Yes, also running `make install` (having set the correct prefix) does indeed solve the problem. There is no need for any change in this project. Thanks again.
