### ISSUE TITLE
Unable to run `mix dialyzer` in new phoenix project

### ISSUE THREAD

**Issue by user453584** [jeremyjh/dialyxir#81]
I've been following the steps in https://github.com/jeremyjh/dialyxir/wiki/Phoenix-Dialyxir-Quickstart for a brand new phoenix project, but all the errors I run into when running `mix dialyzer` are not mentioned there. The following is the complete output of `mix dialyzer` for reference:

```
$ mix dialyzer
Checking PLT...
[:asn1, :bunt, :compiler, :connection, :cowboy, :cowlib, :credo, :crypto,
 :db_connection, :decimal, :dialyxir, :ecto, :eex, :elixir, :gettext, :kernel,
 :logger, :mime, :phoenix, :phoenix_ecto, :phoenix_pubsub, :plug, :poison,
 :poolboy, :postgrex, :public_key, :ranch, :ssl, :stdlib]
PLT is up to date!
Starting Dialyzer
dialyzer args: [check_plt: false,
 init_plt: '/apps/my_app/master/_build/dev/dialyxir_erlang-19.1_elixir-1.4.2_deps-dev.plt',
 files_rec: ['/apps/my_app/master/_build/dev/lib/my_app/ebin'],
 warnings: [:unknown]]
done in 0m4.36s
:0: Unknown function 'Elixir.Endpoint':config_change/2
lib/phoenix/router.ex:2: Function dispatch/2 will never be called
lib/phoenix/router.ex:2: Function match_route/2 has no local return
web/router.ex:1: Function segments/3 will never be called
done (warnings were emitted)
```

Here are the various versions at play:

```
Erlang version: 19.1
Elixir version: 1.4.2
Phoenix version: 1.2.1
```

What is the best way to resolve these issues?

**Comment by jeremyjh** [comment]
Yeah its been awhile since that was written and its a constant struggle to work around upstream bugs. 

You can easily ignore these warnings by using an `ignore_warnings:` file that matches each of those lines. e.g. in your mix.exs  project add:

```elixir
dialyzer: [ignore_warnings: "dialyzer.ignore-warnings"]
```

And then put the offending lines in a file `dialyzer.ignore-warnings`.

**Comment by user453584** [comment]
Ah, okay that's helpful. Thanks!
