### ISSUE TITLE
Passing command line arguments does not work

### ISSUE THREAD

**Issue by leikind** [jeremyjh/dialyxir#85]
Version 0.5.0

```elixir
  def project do
    [
      ...
      dialyzer: [
        plt_add_deps: :transitive,
        ignore_warnings: "dialyzer.ignore-warnings",
        flags: ["--quiet"]
      ]
    ]
  end
```

Running:

```shell
mix dialyzer
Compiling 23 files (.ex)
Generated efrontback app
Checking PLT...
[skipped]
PLT is up to date!
Starting Dialyzer
dialyzer args: [check_plt: false,
 init_plt: 'skipped',
 files_rec: ['skipped'],
 warnings: [:quiet, :unknown]]
:dialyzer.run error: Unknown dialyzer warning option: quiet
```

The docs say: _You can specify any `dialyzer` command line argument with the :flags keyword._

Am I missing anything?

**Comment by jeremyjh** [comment]
Sorry, it is a documentation error; this used to be supported but as of 0.5 we no longer shell out to `dialyzer` so we can't just forward unknown args. I mentioned this in the wiki [article](https://github.com/jeremyjh/dialyxir/wiki/Upgrading-to-0.5) but missed it in the README - sorry about that. I think we can support --quiet though, let's leave this issue open as a request to implement `quiet`.

**Comment by leikind** [comment]
Thank you

**Comment by daveshah** [comment]
@jeremyjh We're doing a PR night tonight at Elixir |> CLE - mind if I open up a PR to implement `quiet`?

**Comment by jeremyjh** [comment]
That would be great, thanks Dave!
