### ISSUE TITLE
:mix in plt_add_apps is ignored when is added as {:dialyxir runtime: false}

### ISSUE THREAD

**Issue by jeremyowensboggs** [jeremyjh/dialyxir#87]
I have a project that has some mix tasks, and so I have added 
`plt_add_apps: [:mix]`
and that takes care of the issues in my mix tasks.  However, if I change the `deps` from:
`{:dialyxir, "0.5.0", only: [:dev, :test]},`
to
`{:dialyxir, "0.5.0", only: [:dev, :test], runtime: false},`
then the mix errors return.

**Comment by jeremyjh** [comment]
Can you please paste the full output from when you run `mix dialyzer` ?

**Comment by jeremyowensboggs** [comment]
With runtime: false
Generated tractor_beam app
In an Umbrella child and no PLT found - building that first.
Checking PLT...
[:asn1, :base64url, :big_query, :bunt, :certifi, :combine, :compiler,
 :connection, :cowboy, :cowlib, :credo, :crypto, :db_connection, :decimal, :eex,
 :elixir, :fs, :gettext, :gproc, :hackney, :httpoison, :idna, :inets, :jose,
 :kernel, :logger, :mariaex, :menu_assets, :metrics, :mime, :mimerl, :phoenix,
 :phoenix_html, :phoenix_live_reload, :phoenix_pubsub, :plug, :poison, :poolboy,
 :public_key, :ranch, :ssl, :ssl_verify_fun, :stdlib, :sweet_xml, :timex,
 :tzdata, :xmerl]
Finding suitable PLTs
Looking up modules in dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt
Looking up modules in dialyxir_erlang-19.3_elixir-1.4.2.plt
Finding applications for dialyxir_erlang-19.3_elixir-1.4.2.plt
Finding modules for dialyxir_erlang-19.3_elixir-1.4.2.plt
Checking 380 modules in dialyxir_erlang-19.3_elixir-1.4.2.plt
Finding applications for dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt
Finding modules for dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt
Copying dialyxir_erlang-19.3_elixir-1.4.2.plt to dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt
Looking up modules in dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt
Checking 380 modules in dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt
Adding 1015 modules to dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt
Starting Dialyzer
dialyzer args: [check_plt: false,
 init_plt: '/Users/jowens/dev/tractor_beam/_build/dev/dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt',
 files_rec: ['/Users/jowens/dev/tractor_beam/_build/dev/lib/tractor_beam/ebin'],
 warnings: [:error_handling, :race_conditions, :unknown]]
done in 0m4.11s
:0: Unknown function 'Elixir.Mix':raise/1
:0: Unknown function 'Elixir.Mix.Project':config/0
lib/mix/tasks/ts_lint.ex:1: Callback info about the 'Elixir.Mix.Task' behaviour is not available
lib/mix/tasks/tsc.ex:1: Callback info about the 'Elixir.Mix.Task' behaviour is not available
done (warnings were emitted)

**Comment by jeremyowensboggs** [comment]
Without runtime: false
Checking PLT...
[:asn1, :base64url, :big_query, :bunt, :certifi, :combine, :compiler,
 :connection, :cowboy, :cowlib, :credo, :crypto, :db_connection, :decimal,
 :dialyxir, :dialyzer, :eex, :elixir, :fs, :gettext, :gproc, :hackney, :hipe,
 :httpoison, :idna, :inets, :jose, :kernel, :logger, :mariaex, :menu_assets,
 :metrics, :mime, :mimerl, :mix, :phoenix, :phoenix_html, :phoenix_live_reload,
 :phoenix_pubsub, :plug, :poison, :poolboy, :public_key, :ranch, :ssl,
 :ssl_verify_fun, :stdlib, :sweet_xml, :timex, :tzdata, ...]
Finding suitable PLTs
Looking up modules in dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt
Finding applications for dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt
Finding modules for dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt
Checking 1395 modules in dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt
Adding 547 modules to dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt
Starting Dialyzer
dialyzer args: [check_plt: false,
 init_plt: '/Users/jowens/dev/tractor_beam/_build/dev/dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt',
 files_rec: ['/Users/jowens/dev/tractor_beam/_build/dev/lib/tractor_beam/ebin',
  '/Users/jowens/dev/tractor_beam/_build/dev/lib/menu_assets/ebin'],
 warnings: [:unknown]]
done in 1m3.74s
lib/plugs/user_auth.ex:29: The pattern {'ok', _@6} can never match the type {'error',_}
lib/plugs/user_auth.ex:44: Function assign_user/2 has no local return
done (warnings were emitted)

**Comment by jeremyowensboggs** [comment]
I don't know if it matters, but it is an umbrella app.  The functional output doesn't seem to change between running it the app/project directory as at the root directory.

**Comment by jeremyowensboggs** [comment]
With runtime: false
Checking PLT...
[:asn1, :base64url, :big_query, :bunt, :certifi, :combine, :compiler,
 :connection, :cowboy, :cowlib, :credo, :crypto, :db_connection, :decimal, :eex,
 :elixir, :fs, :gettext, :gproc, :hackney, :httpoison, :idna, :inets, :jose,
 :kernel, :logger, :mariaex, :menu_assets, :metrics, :mime, :mimerl, :phoenix,
 :phoenix_html, :phoenix_live_reload, :phoenix_pubsub, :plug, :poison, :poolboy,
 :public_key, :ranch, :ssl, :ssl_verify_fun, :stdlib, :sweet_xml, :timex,
 :tzdata, :xmerl]
Finding suitable PLTs
Looking up modules in dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt
Finding applications for dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt
Finding modules for dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt
Removing 547 modules from dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt
Checking 1395 modules in dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt
Starting Dialyzer
dialyzer args: [check_plt: false,
 init_plt: '/Users/jowens/dev/tractor_beam/_build/dev/dialyxir_erlang-19.3_elixir-1.4.2_deps-dev.plt',
 files_rec: ['/Users/jowens/dev/tractor_beam/_build/dev/lib/tractor_beam/ebin',
  '/Users/jowens/dev/tractor_beam/_build/dev/lib/menu_assets/ebin'],
 warnings: [:unknown]]
done in 0m4.11s
:0: Unknown function 'Elixir.Mix':raise/1
:0: Unknown function 'Elixir.Mix.Project':config/0
lib/mix/tasks/ts_lint.ex:1: Callback info about the 'Elixir.Mix.Task' behaviour is not available
lib/mix/tasks/tsc.ex:1: Callback info about the 'Elixir.Mix.Task' behaviour is not available
lib/plugs/user_auth.ex:29: The pattern {'ok', _@6} can never match the type {'error',_}
lib/plugs/user_auth.ex:44: Function assign_user/2 has no local return
done (warnings were emitted)

**Comment by jeremyjh** [comment]
:mix is not added to app list in either case. Is the add_apps in your
parent project?

**Comment by jeremyowensboggs** [comment]
No the settings are in the main project, not the parent project, and it looks like :mix is added without runtime: false
```
     dialyzer: [plt_add_deps: :transitive,
                plt_add_apps: [:mix],
                ignore_warnings: ".dialyzer_ignore",
                flags: ["-Werror_handling", "-Wrace_conditions"]],
```

**Comment by jeremyjh** [comment]
I don't see mix in the app list you pasted with false. Dialyxir settings
need  to be in the umbrella parent.

**Comment by jeremyowensboggs** [comment]
thanks, I'll give that a shot.

**Comment by jeremyowensboggs** [comment]
but the deps remain in the child project(s)?

**Comment by jeremyowensboggs** [comment]
Yup, that did it, thank you for your time and help!

**Comment by jeremyjh** [comment]
I would put the dialyxir dep in the parent but it really won't matter I
don't think. Another way you could solve this is to put :mix in the OTP
applications list in the child project - if it's a production runtime
dependency it needs to be there anyway or it would be left out of release
packages and won't be started.
